### DATA Prepping

In [1]:
!pip install --quiet presidio-analyzer
!pip --quiet install spacy
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
     -- ------------------------------------- 0.8/12.8 MB 3.0 MB/s eta 0:00:04
     ---- ----------------------------------- 1.6/12.8 MB 2.8 MB/s eta 0:00:05
     ------- -------------------------------- 2.4/12.8 MB 3.1 MB/s eta 0:00:04
     ----------- ---------------------------- 3.7/12.8 MB 3.8 MB/s eta 0:00:03
     -------------- ------------------------- 4.7/12.8 MB 4.1 MB/s eta 0:00:02
     ------------------ --------------------- 5.8/12.8 MB 4.2 MB/s eta 0:00:02
     ---------------------- ----------------- 7.1/12.8 MB 4.5 MB/s eta 0:00:02
     ------------------------- -------------- 8.1/12.8 MB 4.6 MB/s eta 0:00:02
     ----------------------------- ---------- 9.4/12.8 MB 4.7 MB/s eta 0:00:01
     -------------------------------- ------- 10.5/12.8 MB 4.8 MB/s eta 0:00:01
     ------------------------------------ --- 11.5/12.8 MB 4.8 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 4.8 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 4.8 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [2]:
import json
import random
import pickle
import matplotlib.pyplot as plt
from tqdm import tqdm
import spacy
from spacy.training.example import Example
from spacy.util import minibatch
from presidio_analyzer import AnalyzerEngine

In [3]:
from utils import *

In [4]:
df_full = pd.read_csv('PII43k.csv', on_bad_lines='skip')

df_full.head()

,Template,Filled Template,Tokenised Filled Template,Tokens
0,"In our video conference, discuss the role of e...","In our video conference, discuss the role of e...","['in', 'our', 'video', 'conference', ',', 'dis...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
1,Could you draft a letter for [NAME_1] to send ...,"Could you draft a letter for Dietrich, Schulis...","['could', 'you', 'draft', 'a', 'letter', 'for'...","['O', 'O', 'O', 'O', 'O', 'O', 'B-NAME', 'I-NA..."
2,Discuss the options for [FULLNAME_1] who wants...,Discuss the options for Jeffery Pfeffer who wa...,"['discuss', 'the', 'options', 'for', 'jeff', '...","['O', 'O', 'O', 'O', 'B-FULLNAME', 'I-FULLNAME..."
3,13. Write a press release announcing [FULLNAME...,13. Write a press release announcing Gayle Wat...,"['13', '.', 'write', 'a', 'press', 'release', ...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-FULLNAM..."
4,9. Develop an inventory management plan for [F...,9. Develop an inventory management plan for Ev...,"['9', '.', 'develop', 'an', 'inventory', 'mana...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-FU..."

In [5]:
cleaned_matches, unique_matches = get_template_tokens(df_full)

def replace_unique_tokens(text, tokens):
	for token in tokens:
		# Match either an underscore with one or more digits or with 'N'
		pattern = r'\[' + token + r'_(?:\d+|N)\]'
		# Replace with the token in square brackets (e.g., "[NAME]")
		text = re.sub(pattern, f'[{token}]', text)
	return text

df_full['Template'] = df_full['Template'].apply(lambda t: replace_unique_tokens(t, cleaned_matches))

# view the first 5 rows of the 'Template' column
df_full['Template'].head()

0    In our video conference, discuss the role of e...
1    Could you draft a letter for [NAME] to send to...
2    Discuss the options for [FULLNAME] who wants t...
3    13. Write a press release announcing [FULLNAME...
4    9. Develop an inventory management plan for [F...
Name: Template, dtype: object

In [6]:
import pandas as pd
import re


list_of_weird_rows = [36484,42606,39778,39591,38894,35859,35398,34377,33200,32786,32633,31525,31171,30957,30419,30129,28097,25492,25335,24531,24497,23920,22670,22152,19842,19644,19461,18718,16604,16297,16239,15847,15775,15549,14604,13642,13103,12358,11358,10344,8652,738,6801,5071,4265,3654,3381,3218,1906,38778,36440,35086,7368,13681,29797,7384,13709,29863,35170,38822,30957]

# Original row count
original_count = len(df_full)
print(f"Original number of rows: {original_count}")

# Drop the rows
df_full = df_full.drop(index=list_of_weird_rows, errors='ignore')

# Reset index to have sequential row numbers
df_full = df_full.reset_index(drop=True)
print(f"Number of rows after dropping weird rows: {len(df_full)}")
print(f"Rows removed: {original_count - len(df_full)}")

# Shuffle df_full
df_full = df_full.sample(frac=1, random_state=42).reset_index(drop=True)

Original number of rows: 42759
Number of rows after dropping weird rows: 42699
Rows removed: 60

In [7]:
df_full.head()

,Template,Filled Template,Tokenised Filled Template,Tokens
0,[FIRSTNAME] needs help designing a user-friend...,Halie needs help designing a user-friendly che...,"['hal', '##ie', 'needs', 'help', 'designing', ...","['B-FIRSTNAME', 'I-FIRSTNAME', 'O', 'O', 'O', ..."
1,Draft a letter to [NAME] explaining the import...,"Draft a letter to Runte, McGlynn and Kautzer e...","['draft', 'a', 'letter', 'to', 'run', '##te', ...","['O', 'O', 'O', 'O', 'B-NAME', 'I-NAME', 'I-NA..."
2,3. Describe the process of conducting an inter...,3. Describe the process of conducting an inter...,"['3', '.', 'describe', 'the', 'process', 'of',...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
3,Can you tell me how companies should handle cu...,Can you tell me how companies should handle cu...,"['can', 'you', 'tell', 'me', 'how', 'companies...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
4,Write a research proposal for [NAME] to study ...,Write a research proposal for Wolf - Reilly to...,"['write', 'a', 'research', 'proposal', 'for', ...","['O', 'O', 'O', 'O', 'O', 'B-NAME', 'I-NAME', ..."

In [8]:
cleaned_matches, unique_matches = get_template_tokens(df_full)
print(unique_matches)
print(len(unique_matches))

{'JOBTITLE', 'ETHEREUMADDRESS', 'LITECOINADDRESS', 'BUILDINGNUMBER', 'ZIPCODE', 'SEXTYPE', 'FULLNAME', 'SECONDARYADDRESS', 'STREET', 'USERNAME', 'USERAGENT', 'DISPLAYNAME', 'MASKEDNUMBER', 'CURRENCYSYMBOL', 'CURRENCYNAME', 'COUNTY', 'FIRSTNAME', 'STREETADDRESS', 'GENDER', 'PIN', 'BITCOINADDRESS', 'STATE', 'IBAN', 'JOBAREA', 'MAC', 'CREDITCARDISSUER', 'ORDINALDIRECTION', 'NUMBER', 'CREDITCARDNUMBER', 'ACCOUNTNAME', 'ACCOUNTNUMBER', 'NAME', 'CURRENCY', 'LASTNAME', 'URL', 'AMOUNT', 'CITY', 'EMAIL', 'SEX', 'IPV6', 'IP', 'IPV4', 'CREDITCARDCVV', 'CURRENCYCODE', 'PASSWORD', 'JOBTYPE', 'BIC', 'NEARBYGPSCOORDINATE', 'JOBDESCRIPTOR'}
49

In [9]:
# Display a few rows to verify the changes
print(df_full[['Template', 'Filled Template']].head())

                                            Template  \
0  [FIRSTNAME] needs help designing a user-friend...
1  Draft a letter to [NAME] explaining the import...
2  3. Describe the process of conducting an inter...
3  Can you tell me how companies should handle cu...
4  Write a research proposal for [NAME] to study ...

                                     Filled Template
0  Halie needs help designing a user-friendly che...
1  Draft a letter to Runte, McGlynn and Kautzer e...
2  3. Describe the process of conducting an inter...
3  Can you tell me how companies should handle cu...
4  Write a research proposal for Wolf - Reilly to...

In [10]:
# Replace any occurrence of "[FULLNAME]" (with optional suffix) in the Template 
# with "[NAME] [NAME]"

df_full['Template'] = df_full['Template'].apply(
	lambda t: re.sub(r'\[FULLNAME(?:_(?:\d+|N))?\]', "[NAME] [NAME]", t)
)

# Verify the changes
print(df_full['Template'].head())

0    [FIRSTNAME] needs help designing a user-friend...
1    Draft a letter to [NAME] explaining the import...
2    3. Describe the process of conducting an inter...
3    Can you tell me how companies should handle cu...
4    Write a research proposal for [NAME] to study ...
Name: Template, dtype: object

In [11]:
# Display a few examples with the token "[FIRSTNAME]" in the Template
fname_examples = df_full[df_full['Template'].str.contains(r'\[FIRSTNAME_1\]', na=False)]

if fname_examples.empty:
	print("No rows found with the token [FIRSTNAME_1]")
else:
	for i, row in fname_examples.head(5).iterrows():
		print("Template:", row["Template"])
		print("Filled Template:", row["Filled Template"])
		print("-" * 60)

No rows found with the token [FIRSTNAME_1]

In [12]:
token_mapping = {
  "LOCATION": [ 
    "STREETADDRESS",
    "SECONDARYADDRESS",
    "BUILDINGNUMBER",
    "STREET",
    "CITY",
    "STATE",
    "COUNTY",
    "NEARBYGPSCOORDINATE",
    "ZIPCODE"
  ],
  "GENDER": [
    "SEXTYPE",
    "SEX"
  ],
  "USERNAME":[
    "DISPLAYNAME"
  ],
  "NAME": [
    "NAME",
    "FIRSTNAME",
    "LASTNAME"
  ],
  "IP": [
    "IPV4",
    "IP",
    "IPV6",
    "MAC"
  ],
  "JOB": [
    "JOBDESCRIPTOR",
    "JOBTYPE",
    "JOBTITLE",
    "JOBAREA"
  ],
  "MASKEDNUMBER": [
    "NUMBER",
    "AMOUNT",
    "ACCOUNTNUMBER",
    "CREDITCARDCVV",
    "PIN",
    "BUILDINGNUMBER"
  ]
}

In [13]:
def replace_tokens_with_category(text, mapping):
	for category, tokens in mapping.items():
		for token in tokens:
			# Replace tokens with a suffix (e.g., [CITY_1] or [CITY_N])
			pattern = r'\[' + token + r'_(?:\d+|N)\]'
			text = re.sub(pattern, f'[{category.upper()}]', text)
			# Replace tokens without a suffix (e.g., [CITY])
			pattern_no_suffix = r'\[' + token + r'\]'
			text = re.sub(pattern_no_suffix, f'[{category.upper()}]', text)
	return text

# Update the 'Template' column in df_full
df_full['Template'] = df_full['Template'].apply(lambda t: replace_tokens_with_category(t, token_mapping))
print(df_full['Template'].head())

_, unique_matches = get_template_tokens(df_full)
print(unique_matches)
print(len(unique_matches))

0    [NAME] needs help designing a user-friendly ch...
1    Draft a letter to [NAME] explaining the import...
2    3. Describe the process of conducting an inter...
3    Can you tell me how companies should handle cu...
4    Write a research proposal for [NAME] to study ...
Name: Template, dtype: object
{'ETHEREUMADDRESS', 'LITECOINADDRESS', 'USERAGENT', 'USERNAME', 'LOCATION', 'MASKEDNUMBER', 'JOB', 'CURRENCYSYMBOL', 'CURRENCYNAME', 'GENDER', 'BITCOINADDRESS', 'IBAN', 'CREDITCARDISSUER', 'ORDINALDIRECTION', 'CREDITCARDNUMBER', 'ACCOUNTNAME', 'NAME', 'CURRENCY', 'URL', 'EMAIL', 'IP', 'CURRENCYCODE', 'PASSWORD', 'BIC'}
24

In [14]:
df_full

,Template,Filled Template,Tokenised Filled Template,Tokens
0,[NAME] needs help designing a user-friendly ch...,Halie needs help designing a user-friendly che...,"['hal', '##ie', 'needs', 'help', 'designing', ...","['B-FIRSTNAME', 'I-FIRSTNAME', 'O', 'O', 'O', ..."
1,Draft a letter to [NAME] explaining the import...,"Draft a letter to Runte, McGlynn and Kautzer e...","['draft', 'a', 'letter', 'to', 'run', '##te', ...","['O', 'O', 'O', 'O', 'B-NAME', 'I-NAME', 'I-NA..."
2,3. Describe the process of conducting an inter...,3. Describe the process of conducting an inter...,"['3', '.', 'describe', 'the', 'process', 'of',...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
3,Can you tell me how companies should handle cu...,Can you tell me how companies should handle cu...,"['can', 'you', 'tell', 'me', 'how', 'companies...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
4,Write a research proposal for [NAME] to study ...,Write a research proposal for Wolf - Reilly to...,"['write', 'a', 'research', 'proposal', 'for', ...","['O', 'O', 'O', 'O', 'O', 'B-NAME', 'I-NAME', ..."
...,...,...,...,...
42694,Can you write a report on the recent developme...,Can you write a report on the recent developme...,"['can', 'you', 'write', 'a', 'report', 'on', '...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
42695,Can you compile a list of top 10 competitors i...,Can you compile a list of top 10 competitors i...,"['can', 'you', 'com', '##pile', 'a', 'list', '...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
42696,Please provide a list of the top 5 corporate g...,Please provide a list of the top 5 corporate g...,"['please', 'provide', 'a', 'list', 'of', 'the'...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
42697,Can you help me with a workplace culture asses...,Can you help me with a workplace culture asses...,"['can', 'you', 'help', 'me', 'with', 'a', 'wor...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
42698,"During our video conference, can you explain h...","During our video conference, can you explain h...","['during', 'our', 'video', 'conference', ',', ...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."

In [15]:
# Count occurrences of each cleaned token in df_full
counts = {}
for token in unique_matches:
    # Adjust pattern to count tokens without numeric suffixes (e.g., "[NAME]")
    pattern = r'\[' + token + r'\]'
    counts[token] = int(df_full["Template"].dropna().str.count(pattern).sum())

# Convert to a DataFrame and sort by count for a nicer display
counts_df = pd.DataFrame(list(counts.items()), columns=['Token', 'Count']).sort_values(by='Count', ascending=False)
counts_df

               Token  Count
16              NAME  55826
4           LOCATION  12114
19             EMAIL   7913
6                JOB   3369
5       MASKEDNUMBER   1467
18               URL    996
3           USERNAME    713
20                IP    541
17          CURRENCY    345
22          PASSWORD    289
9             GENDER    255
8       CURRENCYNAME    215
15       ACCOUNTNAME    215
14  CREDITCARDNUMBER    166
2          USERAGENT    127
21      CURRENCYCODE    101
10    BITCOINADDRESS    101
0    ETHEREUMADDRESS     63
11              IBAN     58
12  CREDITCARDISSUER     43
23               BIC     18
7     CURRENCYSYMBOL     16
1    LITECOINADDRESS     15
13  ORDINALDIRECTION      8

In [16]:
import re

# List of tokens to replace
remove_tokens = [
    "ORDINALDIRECTION", "ACCOUNTNAME", "CURRENCYSYMBOL",
    "CURRENCYNAME", "CURRENCY", "CURRENCYCODE",
    "CREDITCARDISSUER", "ETHEREUMADDRESS", "LITECOINADDRESS", "BITCOINADDRESS","BIC"
]

def unmask_text(text_with_mask, text_without_mask, tokens):
    general_token_pattern = r'\[([A-Z0-9_]+)(?:_(?:\d+|N))?\]'
    matches = list(re.finditer(general_token_pattern, text_with_mask))
    pattern_parts = []
    pos = 0

    for i, match in enumerate(matches):
        # Append literal text (escaped)
        literal_text = re.escape(text_with_mask[pos:match.start()])
        pattern_parts.append(literal_text)

        token_name = match.group(1)
        lookahead = ""
        if token_name in tokens:
            if i + 1 < len(matches):
                next_literal = text_with_mask[match.end():matches[i+1].start()]
                next_token = matches[i+1].group(1)
                if next_literal == "" and next_token not in tokens:
                    lookahead = "(?=\d)"
            # Use a unique group name for each occurrence
            group_name = f"{token_name}_{i}"
            pattern_parts.append(f"(?P<{group_name}>.+?){lookahead}")
        else:
            pattern_parts.append(".+?")
        pos = match.end()

    pattern_parts.append(re.escape(text_with_mask[pos:]))
    final_pattern = ''.join(pattern_parts)
    match_obj = re.fullmatch(final_pattern, text_without_mask)
    if match_obj:
        return match_obj.groupdict()
    return {}

def consolidate_extracted_values(extracted):
    """
    Convert keys like CREDITCARDISSUER_3, CREDITCARDISSUER_7 into a dictionary
    with key 'CREDITCARDISSUER' mapping to a list of values.
    """
    consolidated = {}
    for key, value in extracted.items():
        base = key.split('_')[0]
        consolidated.setdefault(base, []).append(value)
    return consolidated

def replace_tokens(text_with_mask, extracted_values):
    """
    Replace tokens in text_with_mask with corresponding extracted values.
    For tokens appearing multiple times, use a counter to replace them in order.
    """
    counters = {}
    def replacement(match):
        token_name = match.group(1)
        values = extracted_values.get(token_name, [])
        if not values:
            return ""
        idx = counters.get(token_name, 0)
        counters[token_name] = idx + 1
        return values[idx]
    token_regex = r'\[(' + '|'.join(remove_tokens) + r')(?:_(?:\d+|N))?\]'
    return re.sub(token_regex, replacement, text_with_mask)

# Example usage within your loop:
for i, row in df_full.iterrows():
    masked = row['Template']
    filled = row['Filled Template']
    extracted = unmask_text(masked, filled, remove_tokens)
    
    # Consolidate extracted values so that tokens map to lists
    if extracted:
        consolidated = consolidate_extracted_values(extracted)
        unmasked_text = replace_tokens(masked, consolidated)
    else:
        unmasked_text = masked

    if i == -1:
        print("Extracted values (consolidated):", consolidated)
        print("row:", i)
        print("Masked text:", masked)
        print("Filled text:", filled)
        print("-" * 50)
        print("Unmasked text:", unmasked_text)
        print("-" * 50)
        break

    if extracted != {}:
        print("Extracted values (consolidated):", consolidated)
        print("Masked text:", masked)
        print("Filled text:", filled)
        print("-" * 50)
        print("Unmasked text:", unmasked_text)
        print("-" * 50)
        df_full.at[i, 'Template'] = unmasked_text

Extracted values (consolidated): {'CURRENCYNAME': ['Swiss Franc']}
Masked text: What are the tax implications of receiving [MASKEDNUMBER] [CURRENCYNAME] as a gift?
Filled text: What are the tax implications of receiving 799.96 Swiss Franc as a gift?
--------------------------------------------------
Unmasked text: What are the tax implications of receiving [MASKEDNUMBER] Swiss Franc as a gift?
--------------------------------------------------
Extracted values (consolidated): {'CURRENCY': ['Zimbabwe Dollar']}
Masked text: Develop a project budget for [NAME] [NAME] taking into account the [CURRENCY] costs and resources needed.
Filled text: Develop a project budget for Jody Fisher taking into account the Zimbabwe Dollar costs and resources needed.
--------------------------------------------------
Unmasked text: Develop a project budget for [NAME] [NAME] taking into account the Zimbabwe Dollar costs and resources needed.
--------------------------------------------------
Extracted values (consolidated): {'CURRENCY': ['Rand']}
Masked text: Please write a guide on the role of life insurance in estate planning for [NAME], who has a policy worth [MASKEDNUMBER] [CURRENCY].
Filled text: Please write a guide on the role of life insurance in estate planning for Harvey, Schumm and Schinner, who has a policy worth 674.17 Rand.
--------------------------------------------------
Unmasked text: Please write a guide on the role of life insurance in estate planning for [NAME], who has a policy worth [MASKEDNUMBER] Rand.
--------------------------------------------------
Extracted values (consolidated): {'CREDITCARDISSUER': ['discover']}
Masked text: Can you create a list of ethical guidelines for attorneys working with clients' [MASKEDNUMBER] and [CREDITCARDISSUER] information?
Filled text: Can you create a list of ethical guidelines for attorneys working with clients' 528 and discover information?
--------------------------------------------------
Unmasked text: Can you create a list of ethical guidelines for attorneys working with clients' [MASKEDNUMBER] and discover information?
--------------------------------------------------
Extracted values (consolidated): {'CURRENCYNAME': ['Dominican Peso']}
Masked text: Can you help [NAME] with a market penetration strategy? They've got a budget of [MASKEDNUMBER] [CURRENCYNAME].
Filled text: Can you help Cremin - Murphy with a market penetration strategy? They've got a budget of 419.00 Dominican Peso.
--------------------------------------------------
Unmasked text: Can you help [NAME] with a market penetration strategy? They've got a budget of [MASKEDNUMBER] Dominican Peso.
--------------------------------------------------
Extracted values (consolidated): {'CURRENCYCODE': ['KRW']}
Masked text: Write a demand letter for [NAME] regarding the outstanding payment of [MASKEDNUMBER] [CURRENCYCODE] from their client.
Filled text: Write a demand letter for Erdman, Kuhic and Jacobson regarding the outstanding payment of 196.00 KRW from their client.
--------------------------------------------------
Unmasked text: Write a demand letter for [NAME] regarding the outstanding payment of [MASKEDNUMBER] KRW from their client.
--------------------------------------------------
Extracted values (consolidated): {'CURRENCYNAME': ['Som']}
Masked text: Let's create an innovation strategy for [NAME]. They're looking to invest [MASKEDNUMBER] [CURRENCYNAME] in R&D.
Filled text: Let's create an innovation strategy for Wiza - Labadie. They're looking to invest 298.98 Som in R&D.
--------------------------------------------------
Unmasked text: Let's create an innovation strategy for [NAME]. They're looking to invest [MASKEDNUMBER] Som in R&D.
--------------------------------------------------
Extracted values (consolidated): {'CURRENCY': ['Taka']}
Masked text: 7. Prepare a report on the performance of [NAME] [NAME]'s online store, including key metrics such as conversion rate, average order value, and [CURRENCY] revenue.
Filled text: 7. Prepare a report on the performance of Angel Schuppe's online store, including key metrics such as conversion rate, average order value, and Taka revenue.
--------------------------------------------------
Unmasked text: 7. Prepare a report on the performance of [NAME] [NAME]'s online store, including key metrics such as conversion rate, average order value, and Taka revenue.
--------------------------------------------------
Extracted values (consolidated): {'CURRENCY': ['Guyana Dollar']}
Masked text: During the video conference, please discuss the financial strategies for [NAME] [NAME]'s company and the impact of [CURRENCY] fluctuations on their business.
Filled text: During the video conference, please discuss the financial strategies for Delia Veum's company and the impact of Guyana Dollar fluctuations on their business.
--------------------------------------------------
Unmasked text: During the video conference, please discuss the financial strategies for [NAME] [NAME]'s company and the impact of Guyana Dollar fluctuations on their business.
--------------------------------------------------
Extracted values (consolidated): {'CURRENCYCODE': ['XOF']}
Masked text: I need your help to project our sales for the upcoming season. Last year, we had a revenue of [MASKEDNUMBER] [CURRENCYCODE].
Filled text: I need your help to project our sales for the upcoming season. Last year, we had a revenue of 837.16 XOF.
--------------------------------------------------
Unmasked text: I need your help to project our sales for the upcoming season. Last year, we had a revenue of [MASKEDNUMBER] XOF.
--------------------------------------------------
Extracted values (consolidated): {'CURRENCYNAME': ['Philippine Peso']}
Masked text: I'm a bit confused about how to report my [CURRENCYNAME] income. Can you help me out?
Filled text: I'm a bit confused about how to report my Philippine Peso income. Can you help me out?
--------------------------------------------------
Unmasked text: I'm a bit confused about how to report my Philippine Peso income. Can you help me out?
--------------------------------------------------
Extracted values (consolidated): {'CURRENCYCODE': ['ALL']}
Masked text: Could you help me understand the maritime laws for ships using [CURRENCYCODE] for transactions?
Filled text: Could you help me understand the maritime laws for ships using ALL for transactions?
--------------------------------------------------
Unmasked text: Could you help me understand the maritime laws for ships using ALL for transactions?
--------------------------------------------------
Extracted values (consolidated): {'BITCOINADDRESS': ['3d4CV2AGxpur1vzjdaWxRSNn15F'], 'LITECOINADDRESS': ['LvdEBfW8t5M5QYPzDvx52fKo3j']}
Masked text: Write a case study on a cyber law violation involving unauthorized access to an individual's [BITCOINADDRESS] and [LITECOINADDRESS].
Filled text: Write a case study on a cyber law violation involving unauthorized access to an individual's 3d4CV2AGxpur1vzjdaWxRSNn15F and LvdEBfW8t5M5QYPzDvx52fKo3j.
--------------------------------------------------
Unmasked text: Write a case study on a cyber law violation involving unauthorized access to an individual's 3d4CV2AGxpur1vzjdaWxRSNn15F and LvdEBfW8t5M5QYPzDvx52fKo3j.
--------------------------------------------------
Extracted values (consolidated): {'BITCOINADDRESS': ['1cvNPbCeaExwXR4ZLjS4DWs3AAzs5MV'], 'ETHEREUMADDRESS': ['0xc5b8bebffd1d8a1d72ffcb737e1daa4c40ff9b6c']}
Masked text: Could you help me understand the tax laws for cryptocurrency transactions, like [BITCOINADDRESS] or [ETHEREUMADDRESS]?
Filled text: Could you help me understand the tax laws for cryptocurrency transactions, like 1cvNPbCeaExwXR4ZLjS4DWs3AAzs5MV or 0xc5b8bebffd1d8a1d72ffcb737e1daa4c40ff9b6c?
--------------------------------------------------
Unmasked text: Could you help me understand the tax laws for cryptocurrency transactions, like 1cvNPbCeaExwXR4ZLjS4DWs3AAzs5MV or 0xc5b8bebffd1d8a1d72ffcb737e1daa4c40ff9b6c?
--------------------------------------------------
Extracted values (consolidated): {'CURRENCY': ['Aruban Guilder']}
Masked text: I need to update our company's budget. Can you help me analyze our [CURRENCY] expenses and identify areas for cost reduction?
Filled text: I need to update our company's budget. Can you help me analyze our Aruban Guilder expenses and identify areas for cost reduction?
--------------------------------------------------
Unmasked text: I need to update our company's budget. Can you help me analyze our Aruban Guilder expenses and identify areas for cost reduction?
--------------------------------------------------
Extracted values (consolidated): {'CURRENCY': ['Rwanda Franc']}
Masked text: Write a promissory note for a loan of [MASKEDNUMBER] [CURRENCY] from [NAME] to [NAME].
Filled text: Write a promissory note for a loan of 22.44 Rwanda Franc from Hickle - Conn to Mann, Morar and Luettgen.
--------------------------------------------------
Unmasked text: Write a promissory note for a loan of [MASKEDNUMBER] Rwanda Franc from [NAME] to [NAME].
--------------------------------------------------
Extracted values (consolidated): {'LITECOINADDRESS': ['34DdeP1uArtKgfgSkakGkKcQQ61']}
Masked text: Develop a training module for law enforcement on how to handle cases involving cryptocurrency transactions like [LITECOINADDRESS].
Filled text: Develop a training module for law enforcement on how to handle cases involving cryptocurrency transactions like 34DdeP1uArtKgfgSkakGkKcQQ61.
--------------------------------------------------
Unmasked text: Develop a training module for law enforcement on how to handle cases involving cryptocurrency transactions like 34DdeP1uArtKgfgSkakGkKcQQ61.
--------------------------------------------------
Extracted values (consolidated): {'CURRENCY': ['Metical']}
Masked text: What are the legal requirements for banks when it comes to reporting suspicious transactions involving large [MASKEDNUMBER] [CURRENCY] transfers?
Filled text: What are the legal requirements for banks when it comes to reporting suspicious transactions involving large 419.06 Metical transfers?
--------------------------------------------------
Unmasked text: What are the legal requirements for banks when it comes to reporting suspicious transactions involving large [MASKEDNUMBER] Metical transfers?
--------------------------------------------------
Extracted values (consolidated): {'CURRENCY': ['Nuevo Sol']}
Masked text: Analyze the benefits of setting up a trust for [NAME] [NAME], with their assets worth [MASKEDNUMBER] [CURRENCY].
Filled text: Analyze the benefits of setting up a trust for Bob Carter-Nader, with their assets worth 450.50 Nuevo Sol.
--------------------------------------------------
Unmasked text: Analyze the benefits of setting up a trust for [NAME] [NAME], with their assets worth [MASKEDNUMBER] Nuevo Sol.
--------------------------------------------------
Extracted values (consolidated): {'CURRENCYNAME': ['Armenian Dram']}
Masked text: Write an email to [NAME] at [EMAIL] discussing the implications of the recent anti-trust ruling on the [CURRENCYNAME] market.
Filled text: Write an email to Paucek Group at Maximilian.Paucek-Hintz@yahoo.com discussing the implications of the recent anti-trust ruling on the Armenian Dram market.
--------------------------------------------------
Unmasked text: Write an email to [NAME] at [EMAIL] discussing the implications of the recent anti-trust ruling on the Armenian Dram market.
--------------------------------------------------
Extracted values (consolidated): {'ACCOUNTNAME': ['Money Market Account']}
Masked text: 4. Write a step-by-step guide for integrating [ACCOUNTNAME] into an eCommerce website.
Filled text: 4. Write a step-by-step guide for integrating Money Market Account into an eCommerce website.
--------------------------------------------------
Unmasked text: 4. Write a step-by-step guide for integrating Money Market Account into an eCommerce website.
--------------------------------------------------
Extracted values (consolidated): {'CURRENCY': ['Pakistan Rupee']}
Masked text: I'm curious about the average compensation for personal injury cases in [CURRENCY]. Can you find that information?
Filled text: I'm curious about the average compensation for personal injury cases in Pakistan Rupee. Can you find that information?
--------------------------------------------------
Unmasked text: I'm curious about the average compensation for personal injury cases in Pakistan Rupee. Can you find that information?
--------------------------------------------------
Extracted values (consolidated): {'CURRENCYCODE': ['AZN']}
Masked text: Write an email to [NAME] at [EMAIL] discussing the advantages and disadvantages of investing in the [CURRENCYCODE] market.
Filled text: Write an email to Lynch, Bauch and Kub at Cleta3@hotmail.com discussing the advantages and disadvantages of investing in the AZN market.
--------------------------------------------------
Unmasked text: Write an email to [NAME] at [EMAIL] discussing the advantages and disadvantages of investing in the AZN market.
--------------------------------------------------
Extracted values (consolidated): {'CURRENCY': ['Cordoba Oro'], 'BITCOINADDRESS': ['3FpFB2dMChmg28EowWKRT1LVXc7GDiGxBi']}
Masked text: Hey, can you create a summary of the case where [NAME] was accused of laundering [MASKEDNUMBER] [CURRENCY] through [BITCOINADDRESS]?
Filled text: Hey, can you create a summary of the case where Brekke and Sons was accused of laundering 28.20 Cordoba Oro through 3FpFB2dMChmg28EowWKRT1LVXc7GDiGxBi?
--------------------------------------------------
Unmasked text: Hey, can you create a summary of the case where [NAME] was accused of laundering [MASKEDNUMBER] Cordoba Oro through 3FpFB2dMChmg28EowWKRT1LVXc7GDiGxBi?
--------------------------------------------------
Extracted values (consolidated): {'CURRENCYNAME': ['Yemeni Rial']}
Masked text: Hi! Can you create a marketing plan for [NAME] to target their business in the [CURRENCYNAME] market?
Filled text: Hi! Can you create a marketing plan for McDermott - Powlowski to target their business in the Yemeni Rial market?
--------------------------------------------------
Unmasked text: Hi! Can you create a marketing plan for [NAME] to target their business in the Yemeni Rial market?
--------------------------------------------------
Extracted values (consolidated): {'BITCOINADDRESS': ['3czNuNsCAJ67v5g3cGmQuC8SyscVesbR58Vkauxr'], 'ETHEREUMADDRESS': ['0xc90f5807b8fab6de21dbba2ee7aa64aab568dfd2']}
Masked text: Analyze the potential risks of investing in cryptocurrency for [NAME], focusing on [BITCOINADDRESS] and [ETHEREUMADDRESS].
Filled text: Analyze the potential risks of investing in cryptocurrency for Langworth, Lemke and Johns, focusing on 3czNuNsCAJ67v5g3cGmQuC8SyscVesbR58Vkauxr and 0xc90f5807b8fab6de21dbba2ee7aa64aab568dfd2.
--------------------------------------------------
Unmasked text: Analyze the potential risks of investing in cryptocurrency for [NAME], focusing on 3czNuNsCAJ67v5g3cGmQuC8SyscVesbR58Vkauxr and 0xc90f5807b8fab6de21dbba2ee7aa64aab568dfd2.
--------------------------------------------------
Extracted values (consolidated): {'CURRENCYCODE': ['CHF']}
Masked text: Create a step-by-step guide for [NAME] on how to optimize the checkout process on their eCommerce website [URL] using [CURRENCYCODE].
Filled text: Create a step-by-step guide for Howell, Breitenberg and Nolan on how to optimize the checkout process on their eCommerce website https://tall-thumb.com using CHF.
--------------------------------------------------
Unmasked text: Create a step-by-step guide for [NAME] on how to optimize the checkout process on their eCommerce website [URL] using CHF.
--------------------------------------------------
Extracted values (consolidated): {'CURRENCY': ['Congolese Franc']}
Masked text: Draft a purchase agreement for [NAME], including the property details at [LOCATION] [LOCATION] and a down payment of [MASKEDNUMBER] [CURRENCY].
Filled text: Draft a purchase agreement for Kassulke, Simonis and Cole, including the property details at 4044 Jast Isle and a down payment of 854.87 Congolese Franc.
--------------------------------------------------
Unmasked text: Draft a purchase agreement for [NAME], including the property details at [LOCATION] [LOCATION] and a down payment of [MASKEDNUMBER] Congolese Franc.
--------------------------------------------------
Extracted values (consolidated): {'CURRENCYNAME': ['Gourde']}
Masked text: Could you create a financial plan for [NAME]'s company, outlining the use of funds after raising [MASKEDNUMBER] [CURRENCYNAME] in equity financing?
Filled text: Could you create a financial plan for Morissette, Becker and Kassulke's company, outlining the use of funds after raising 272.82 Gourde in equity financing?
--------------------------------------------------
Unmasked text: Could you create a financial plan for [NAME]'s company, outlining the use of funds after raising [MASKEDNUMBER] Gourde in equity financing?
--------------------------------------------------
Extracted values (consolidated): {'ACCOUNTNAME': ['Personal Loan Account']}
Masked text: Please create a training module on the ethical handling of clients' [ACCOUNTNAME] and [MASKEDNUMBER] information in legal practice.
Filled text: Please create a training module on the ethical handling of clients' Personal Loan Account and 25911508 information in legal practice.
--------------------------------------------------
Unmasked text: Please create a training module on the ethical handling of clients' Personal Loan Account and [MASKEDNUMBER] information in legal practice.
--------------------------------------------------
Extracted values (consolidated): {'CURRENCYCODE': ['MVR', 'OMR']}
Masked text: Hey, let's create a pricing model for [NAME] that takes into account the currency rates from [CURRENCYCODE] to [CURRENCYCODE].
Filled text: Hey, let's create a pricing model for Volkman, Satterfield and Buckridge that takes into account the currency rates from MVR to OMR.
--------------------------------------------------
Unmasked text: Hey, let's create a pricing model for [NAME] that takes into account the currency rates from MVR to OMR.
--------------------------------------------------
Extracted values (consolidated): {'CURRENCYNAME': ['Australian Dollar']}
Masked text: Can you prepare a report for [NAME] on the legal requirements for businesses operating in the [CURRENCYNAME] market?
Filled text: Can you prepare a report for Kiehn and Sons on the legal requirements for businesses operating in the Australian Dollar market?
--------------------------------------------------
Unmasked text: Can you prepare a report for [NAME] on the legal requirements for businesses operating in the Australian Dollar market?
--------------------------------------------------
Extracted values (consolidated): {'CURRENCY': ['Philippine Peso']}
Masked text: Hey, can you create a list of potential acquisition targets for a company with a budget of [MASKEDNUMBER] [CURRENCY]?
Filled text: Hey, can you create a list of potential acquisition targets for a company with a budget of 810.64 Philippine Peso?
--------------------------------------------------
Unmasked text: Hey, can you create a list of potential acquisition targets for a company with a budget of [MASKEDNUMBER] Philippine Peso?
--------------------------------------------------
Extracted values (consolidated): {'CURRENCYNAME': ['Jordanian Dinar']}
Masked text: Can you draft a legal brief on the anti-trust case involving the merger of two large companies in the [CURRENCYNAME] market?
Filled text: Can you draft a legal brief on the anti-trust case involving the merger of two large companies in the Jordanian Dinar market?
--------------------------------------------------

In [17]:
df_full.head()

,Template,Filled Template,Tokenised Filled Template,Tokens
0,[NAME] needs help designing a user-friendly ch...,Halie needs help designing a user-friendly che...,"['hal', '##ie', 'needs', 'help', 'designing', ...","['B-FIRSTNAME', 'I-FIRSTNAME', 'O', 'O', 'O', ..."
1,Draft a letter to [NAME] explaining the import...,"Draft a letter to Runte, McGlynn and Kautzer e...","['draft', 'a', 'letter', 'to', 'run', '##te', ...","['O', 'O', 'O', 'O', 'B-NAME', 'I-NAME', 'I-NA..."
2,3. Describe the process of conducting an inter...,3. Describe the process of conducting an inter...,"['3', '.', 'describe', 'the', 'process', 'of',...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
3,Can you tell me how companies should handle cu...,Can you tell me how companies should handle cu...,"['can', 'you', 'tell', 'me', 'how', 'companies...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
4,Write a research proposal for [NAME] to study ...,Write a research proposal for Wolf - Reilly to...,"['write', 'a', 'research', 'proposal', 'for', ...","['O', 'O', 'O', 'O', 'O', 'B-NAME', 'I-NAME', ..."

In [18]:
id = 2375
masked = df_full["Template"][id]
filled = df_full["Filled Template"][id]
extracted_values = unmask_text(masked, filled, remove_tokens)
unmasked_text = replace_tokens(masked, extracted_values)

print("Template:")
print(masked)
print("\nFilled Template:")
print(filled)

Template:
I'm curious, what's the market share of [NAME] compared to [NAME]?

Filled Template:
I'm curious, what's the market share of Maggio - Rogahn compared to Bayer, Kessler and Effertz?

In [19]:
id = 39654
masked = df_full["Template"][id]
filled = df_full["Filled Template"][id]
extracted_values = unmask_text(masked, filled, remove_tokens)
unmasked_text = replace_tokens(masked, extracted_values)

print("Template:")
print(masked)
print("\nFilled Template:")
print(filled)

Template:
I'd like to send out an email to [EMAIL] about the upcoming corporate training session. Can you help me write it?

Filled Template:
I'd like to send out an email to Nella.Lindgren@hotmail.com about the upcoming corporate training session. Can you help me write it?

In [20]:
id = 38860
masked = df_full["Template"][id]
filled = df_full["Filled Template"][id]
extracted_values = unmask_text(masked, filled, remove_tokens)
unmasked_text = replace_tokens(masked, extracted_values)

print("Template:")
print(masked)
print("\nFilled Template:")
print(filled)

Template:
Could you explain the four main themes of existential therapy mentioned in this article I found at [URL]?

Filled Template:
Could you explain the four main themes of existential therapy mentioned in this article I found at https://yummy-glasses.org?

In [21]:
# Count the labeled items in the DataFrame
total_labeled_items = count_labeled_items(df_full)
print(f"Total number of labeled items: {total_labeled_items}")
print("Number of rows in df_full:", df_full.shape[0])

Total number of labeled items: 83834
Number of rows in df_full: 42699

In [22]:
df_full.to_csv("ourdata.csv", index=False)

## AWS Comprehend dataprepping START

In [23]:
# AWS Comprehend dataprepping
aws_prepping = df_full.copy()
aws_prepping = aws_prepping.drop(columns=['Tokenised Filled Template', 'Tokens'] )
aws_prepping

,Template,Filled Template
0,[NAME] needs help designing a user-friendly ch...,Halie needs help designing a user-friendly che...
1,Draft a letter to [NAME] explaining the import...,"Draft a letter to Runte, McGlynn and Kautzer e..."
2,3. Describe the process of conducting an inter...,3. Describe the process of conducting an inter...
3,Can you tell me how companies should handle cu...,Can you tell me how companies should handle cu...
4,Write a research proposal for [NAME] to study ...,Write a research proposal for Wolf - Reilly to...
...,...,...
42694,Can you write a report on the recent developme...,Can you write a report on the recent developme...
42695,Can you compile a list of top 10 competitors i...,Can you compile a list of top 10 competitors i...
42696,Please provide a list of the top 5 corporate g...,Please provide a list of the top 5 corporate g...
42697,Can you help me with a workplace culture asses...,Can you help me with a workplace culture asses...
42698,"During our video conference, can you explain h...","During our video conference, can you explain h..."

In [24]:
# Count occurrences of each cleaned token in df_full
counts = {}
for token in unique_matches:
    # Adjust pattern to count tokens without numeric suffixes (e.g., "[NAME]")
    pattern = r'\[' + token + r'\]'
    counts[token] = int(aws_prepping["Template"].dropna().str.count(pattern).sum())

# Convert to a DataFrame and sort by count for a nicer display
counts_df = pd.DataFrame(list(counts.items()), columns=['Token', 'Count']).sort_values(by='Count', ascending=False)
counts_df

               Token  Count
16              NAME  55826
4           LOCATION  12114
19             EMAIL   7913
6                JOB   3369
5       MASKEDNUMBER   1467
18               URL    996
3           USERNAME    713
20                IP    541
22          PASSWORD    289
9             GENDER    255
14  CREDITCARDNUMBER    166
2          USERAGENT    127
11              IBAN     58
7     CURRENCYSYMBOL      0
1    LITECOINADDRESS      0
0    ETHEREUMADDRESS      0
15       ACCOUNTNAME      0
13  ORDINALDIRECTION      0
12  CREDITCARDISSUER      0
10    BITCOINADDRESS      0
8       CURRENCYNAME      0
17          CURRENCY      0
21      CURRENCYCODE      0
23               BIC      0

In [25]:
# # Define list of problematic row indices
# list_of_weird_rows = [36484,42606,39778,39591,38894,35859,35398,34377,33200,32786,32633,31525,31171,30957,30419,30129,28097,25492,25335,24531,24497,23920,22670,22152,19842,19644,19461,18718,16604,16297,16239,15847,15775,15549,14604,13642,13103,12358,11358,10344,8652,738,6801,5071,4265,3654,3381,3218,1906,38778,36440,35086,7368,13681,29797,7384,13709,29863,35170,38822,30957]

# # Remove duplicates
# list_of_weird_rows = list(set(list_of_weird_rows))
# print(f"Number of rows in list_of_weird_rows: {len(list_of_weird_rows)}")

# # Check if these rows actually exist in the DataFrame
# existing_indices = set(list_of_weird_rows).intersection(set(aws_prepping.index))
# print(f"Number of weird rows found in DataFrame: {len(existing_indices)}")

# # Original row count
# original_count = len(aws_prepping)
# print(f"Original number of rows: {original_count}")

# # Drop the rows
# aws_prepping = aws_prepping.drop(index=list_of_weird_rows, errors='ignore')

# # Reset index to have sequential row numbers
# aws_prepping = aws_prepping.reset_index(drop=True)
# print(f"Number of rows after dropping weird rows: {len(aws_prepping)}")
# print(f"Rows removed: {original_count - len(aws_prepping)}")

# aws_prepping.head()

# df_full = aws_prepping.copy()

In [26]:
# Find rows containing [BIC] in the Template column
bic_rows = aws_prepping[aws_prepping["Template"].str.contains(r"\[BIC\]", na=False)]

if len(bic_rows) > 0:
	print(f"Found {len(bic_rows)} rows containing BIC:")
	for idx, row in bic_rows.iterrows():
		print(f"\nRow Index: {idx}")
		print(f"Template: {row['Template']}")
		print(f"Filled Template: {row['Filled Template']}")
		print("-" * 80)
else:
	print("No rows containing [BIC] found in the Template column.")

# Check if BIC is in any of the other fields
for idx, row in aws_prepping.iterrows():
	if "BIC" in str(row["Filled Template"]) and "BIC" not in str(row["Template"]):
		print(f"\nFound BIC in Filled Template but not in Template at row {idx}:")
		print(f"Template: {row['Template']}")
		print(f"Filled Template: {row['Filled Template']}")
		print("-" * 80)

No rows containing [BIC] found in the Template column.

In [27]:
# Count occurrences of each cleaned token in df_full
counts = {}
for token in unique_matches:
    # Adjust pattern to count tokens without numeric suffixes (e.g., "[NAME]")
    pattern = r'\[' + token + r'\]'
    counts[token] = int(aws_prepping["Template"].dropna().str.count(pattern).sum())

# Convert to a DataFrame and sort by count for a nicer display
counts_df = pd.DataFrame(list(counts.items()), columns=['Token', 'Count']).sort_values(by='Count', ascending=False)
counts_df

               Token  Count
16              NAME  55826
4           LOCATION  12114
19             EMAIL   7913
6                JOB   3369
5       MASKEDNUMBER   1467
18               URL    996
3           USERNAME    713
20                IP    541
22          PASSWORD    289
9             GENDER    255
14  CREDITCARDNUMBER    166
2          USERAGENT    127
11              IBAN     58
7     CURRENCYSYMBOL      0
1    LITECOINADDRESS      0
0    ETHEREUMADDRESS      0
15       ACCOUNTNAME      0
13  ORDINALDIRECTION      0
12  CREDITCARDISSUER      0
10    BITCOINADDRESS      0
8       CURRENCYNAME      0
17          CURRENCY      0
21      CURRENCYCODE      0
23               BIC      0

In [28]:
aws_prepping["Filled Template"][740]

'Draft a divorce settlement for Jan Dach and Paula Fisher IV, taking into account their joint bank account 11971664.'

In [29]:
import re
import pandas as pd

def transform_dataframe(df, doc_name="aws_prepping.csv"):
    # This regex matches placeholders like [NAME], [EMAIL], [ANYTHING_123], etc.
    placeholder_pattern = re.compile(r'(\[[^\]]+\])')
    annotation_rows = []

    for i, row in df.iterrows():
        template_text = str(row["Template"])
        filled_text   = str(row["Filled Template"])
        
        # Split template into chunks + placeholders, e.g.:
        # ["Could you draft a letter for ", "[NAME]", " to send to ", "[EMAIL]", ...]
        parts = placeholder_pattern.split(template_text)
        
        # We'll keep track of where we are in the filled_text
        filled_pos = 0
        
        if i == 741:
            print("Row 741 details:")
            print(row.to_dict())
            print("Parts:", parts)
        if i == 740:
            print("Row 740 details:")
            print(row.to_dict())
            print("Parts:", parts)


        # Walk through each chunk or placeholder
        for idx, part in enumerate(parts):
            # Check if 'part' is a placeholder (e.g., "[NAME]")
            if placeholder_pattern.match(part):
                # Extract the entity type from the placeholder text, e.g. "[NAME]" -> "NAME"
                entity_type = part.strip("[]")
                
                # Find the next literal chunk in parts (the text that comes after this placeholder)
                next_chunk = ""
                for j in range(idx + 1, len(parts)):
                    if not placeholder_pattern.match(parts[j]):
                        next_chunk = parts[j]
                        break
                
                # If there's no next chunk, the replaced text goes until the end of filled_text
                if next_chunk == "":
                    replaced_text = filled_text[filled_pos:]
                    begin_offset = filled_pos
                    end_offset   = filled_pos + len(replaced_text)
                    
                    if replaced_text.strip():
                        annotation_rows.append([
                            doc_name,   # File
                            i,          # Line (row index)
                            begin_offset,
                            end_offset,
                            entity_type
                        ])
                    
                    filled_pos = end_offset
                
                else:
                    # Instead of simply using find(), check if the filled text ends with the next chunk.
                    # This avoids capturing an occurrence of next_chunk that is embedded within the replaced text.
                    if filled_text.endswith(next_chunk):
                        next_chunk_pos = filled_text.rfind(next_chunk, filled_pos)
                    else:
                        next_chunk_pos = filled_text.find(next_chunk, filled_pos)
                    
                    if next_chunk_pos == -1:
                        # If not found, assume the replaced text is everything to the end
                        replaced_text = filled_text[filled_pos:]
                        begin_offset  = filled_pos
                        end_offset    = filled_pos + len(replaced_text)
                        
                        if replaced_text.strip():
                            annotation_rows.append([
                                doc_name,
                                i,
                                begin_offset,
                                end_offset,
                                entity_type
                            ])
                        filled_pos = end_offset
                    else:
                        # The replaced text is everything from filled_pos up to where next_chunk starts
                        replaced_text = filled_text[filled_pos:next_chunk_pos]
                        begin_offset  = filled_pos
                        end_offset    = next_chunk_pos
                        
                        if replaced_text.strip():
                            annotation_rows.append([
                                doc_name,
                                i,
                                begin_offset,
                                end_offset,
                                entity_type
                            ])
                        
                        filled_pos = next_chunk_pos
            
            else:
                # This is a normal text chunk (not a placeholder).
                pos = filled_text.find(part, filled_pos)
                if pos != -1:
                    filled_pos = pos + len(part)
                else:
                    pass

    ann_df = pd.DataFrame(annotation_rows, columns=["File", "Line", "Begin Offset", "End Offset", "Type"])
    
    return ann_df

# Transform the DataFrame and save the resulting CSV
annotations_df = transform_dataframe(aws_prepping)
print(annotations_df.head())
print("Unique types:", annotations_df["Type"].unique())
print(len(annotations_df["Type"].unique()))
print(len(annotations_df))
print(annotations_df["Type"].value_counts())

Row 740 details:
{'Template': 'Draft a divorce settlement for [NAME] [NAME] and [NAME] [NAME], taking into account their joint bank account [MASKEDNUMBER].', 'Filled Template': 'Draft a divorce settlement for Jan Dach and Paula Fisher IV, taking into account their joint bank account 11971664.'}
Parts: ['Draft a divorce settlement for ', '[NAME]', ' ', '[NAME]', ' and ', '[NAME]', ' ', '[NAME]', ', taking into account their joint bank account ', '[MASKEDNUMBER]', '.']
Row 741 details:
{'Template': "Hey, I've been struggling with stress lately, can you send me a mindfulness-based therapy guide to my email at [EMAIL]?", 'Filled Template': "Hey, I've been struggling with stress lately, can you send me a mindfulness-based therapy guide to my email at Nicklaus_Erdman91@hotmail.com?"}
Parts: ["Hey, I've been struggling with stress lately, can you send me a mindfulness-based therapy guide to my email at ", '[EMAIL]', '?']
               File  Line  Begin Offset  End Offset   Type
0  aws_prepping.csv     0             0           5   NAME
1  aws_prepping.csv     1            18          44   NAME
2  aws_prepping.csv     2            58          64   NAME
3  aws_prepping.csv     2            65          71   NAME
4  aws_prepping.csv     3            53          76  EMAIL
Unique types: ['NAME' 'EMAIL' 'LOCATION' 'MASKEDNUMBER' 'URL' 'JOB' 'IP' 'USERNAME'
 'GENDER' 'USERAGENT' 'CREDITCARDNUMBER' 'PASSWORD' 'IBAN']
13
83834
Type
NAME                55826
LOCATION            12114
EMAIL                7913
JOB                  3369
MASKEDNUMBER         1467
URL                   996
USERNAME              713
IP                    541
PASSWORD              289
GENDER                255
CREDITCARDNUMBER      166
USERAGENT             127
IBAN                   58
Name: count, dtype: int64

In [30]:
aws_prepping["Filled Template"][740]

'Draft a divorce settlement for Jan Dach and Paula Fisher IV, taking into account their joint bank account 11971664.'

In [31]:
counts = {}
for token in unique_matches:
    # Adjust pattern to count tokens without numeric suffixes (e.g., "[NAME]")
    pattern = r'\[' + token + r'\]'
    counts[token] = int(aws_prepping["Template"].dropna().str.count(pattern).sum())

# Convert to a DataFrame and sort by count for a nicer display
counts_df = pd.DataFrame(list(counts.items()), columns=['Token', 'Count']).sort_values(by='Count', ascending=False)
counts_df

               Token  Count
16              NAME  55826
4           LOCATION  12114
19             EMAIL   7913
6                JOB   3369
5       MASKEDNUMBER   1467
18               URL    996
3           USERNAME    713
20                IP    541
22          PASSWORD    289
9             GENDER    255
14  CREDITCARDNUMBER    166
2          USERAGENT    127
11              IBAN     58
7     CURRENCYSYMBOL      0
1    LITECOINADDRESS      0
0    ETHEREUMADDRESS      0
15       ACCOUNTNAME      0
13  ORDINALDIRECTION      0
12  CREDITCARDISSUER      0
10    BITCOINADDRESS      0
8       CURRENCYNAME      0
17          CURRENCY      0
21      CURRENCYCODE      0
23               BIC      0

In [32]:
aws_prepping["Filled Template"][740]

'Draft a divorce settlement for Jan Dach and Paula Fisher IV, taking into account their joint bank account 11971664.'

In [33]:
def mask_text_using_annotations(text, anns):
    # Sort annotations in reverse order of Begin Offset to avoid shifting issues.
    for ann in sorted(anns, key=lambda x: x["Begin Offset"], reverse=True):
        start = ann["Begin Offset"]
        end = ann["End Offset"]
        
        # Check for valid offset ranges.
        if start < 0 or end > len(text):
            print(f"Warning: Annotation offsets {start}-{end} are out of bounds for text length {len(text)}")
            continue

        # Replace the span with the masked placeholder.
        text = text[:start] + f"[{ann['Type']}]" + text[end:]
    
    return text

def apply_masking(row):
    # Retrieve all annotations corresponding to the current row.
    # Subtract 2 from the row index to match the Line number in annotations_df
    line_num = row.name
    anns = annotations_df[annotations_df["Line"] == line_num].to_dict(orient="records")
    if anns:
        return mask_text_using_annotations(row["Filled Template"], anns)
    return row["Filled Template"]

tqdm.pandas(desc="Applying masking")
aws_prepping["Masked Filled Template"] = aws_prepping.progress_apply(apply_masking, axis=1)

Applying masking: 100%|██████████| 42699/42699 [00:22<00:00, 1938.43it/s]

In [34]:
aws_prepping["Filled Template"][740]

'Draft a divorce settlement for Jan Dach and Paula Fisher IV, taking into account their joint bank account 11971664.'

In [35]:
annotations_df[annotations_df["Line"] == id]

                   File   Line  Begin Offset  End Offset Type
76405  aws_prepping.csv  38860            99         124  URL

In [36]:
annotations_df

                   File   Line  Begin Offset  End Offset      Type
0      aws_prepping.csv      0             0           5      NAME
1      aws_prepping.csv      1            18          44      NAME
2      aws_prepping.csv      2            58          64      NAME
3      aws_prepping.csv      2            65          71      NAME
4      aws_prepping.csv      3            53          76     EMAIL
...                 ...    ...           ...         ...       ...
83829  aws_prepping.csv  42696            71          82      NAME
83830  aws_prepping.csv  42697            56          72      NAME
83831  aws_prepping.csv  42697            95         111  LOCATION
83832  aws_prepping.csv  42698            76          82      NAME
83833  aws_prepping.csv  42698            83          90      NAME

[83834 rows x 5 columns]

In [37]:
aws_prepping

,Template,Filled Template,Masked Filled Template
0,[NAME] needs help designing a user-friendly ch...,Halie needs help designing a user-friendly che...,[NAME] needs help designing a user-friendly ch...
1,Draft a letter to [NAME] explaining the import...,"Draft a letter to Runte, McGlynn and Kautzer e...",Draft a letter to [NAME] explaining the import...
2,3. Describe the process of conducting an inter...,3. Describe the process of conducting an inter...,3. Describe the process of conducting an inter...
3,Can you tell me how companies should handle cu...,Can you tell me how companies should handle cu...,Can you tell me how companies should handle cu...
4,Write a research proposal for [NAME] to study ...,Write a research proposal for Wolf - Reilly to...,Write a research proposal for [NAME] to study ...
...,...,...,...
42694,Can you write a report on the recent developme...,Can you write a report on the recent developme...,Can you write a report on the recent developme...
42695,Can you compile a list of top 10 competitors i...,Can you compile a list of top 10 competitors i...,Can you compile a list of top 10 competitors i...
42696,Please provide a list of the top 5 corporate g...,Please provide a list of the top 5 corporate g...,Please provide a list of the top 5 corporate g...
42697,Can you help me with a workplace culture asses...,Can you help me with a workplace culture asses...,Can you help me with a workplace culture asses...
42698,"During our video conference, can you explain h...","During our video conference, can you explain h...","During our video conference, can you explain h..."

In [38]:
id = 3218

In [39]:
aws_prepping["Masked Filled Template"][id]

'Can you write a guide on the role of a family therapist for [NAME]?'

In [40]:
aws_prepping["Template"][id]

'Can you write a guide on the role of a family therapist for [NAME]?'

In [41]:
aws_prepping["Filled Template"][id]

'Can you write a guide on the role of a family therapist for McKenzie LLC?'

In [42]:
aws_prepping.head()

,Template,Filled Template,Masked Filled Template
0,[NAME] needs help designing a user-friendly ch...,Halie needs help designing a user-friendly che...,[NAME] needs help designing a user-friendly ch...
1,Draft a letter to [NAME] explaining the import...,"Draft a letter to Runte, McGlynn and Kautzer e...",Draft a letter to [NAME] explaining the import...
2,3. Describe the process of conducting an inter...,3. Describe the process of conducting an inter...,3. Describe the process of conducting an inter...
3,Can you tell me how companies should handle cu...,Can you tell me how companies should handle cu...,Can you tell me how companies should handle cu...
4,Write a research proposal for [NAME] to study ...,Write a research proposal for Wolf - Reilly to...,Write a research proposal for [NAME] to study ...

In [43]:
# Compare the two strings
counter = 0
for i, row in aws_prepping.iterrows():
    masked = aws_prepping["Masked Filled Template"][i]
    template = aws_prepping["Template"][i]

    # Check if they are equal
    if masked != template:
        print("="*80)
        print(f"Masked Filled Template at index {i}:")
        print(masked)
        print(f"\nTemplate at index {i}:")
        print(template)
        print(f"\nOrginal Filled Template at index {i}:")
        print(aws_prepping["Filled Template"][i])
        print("\nThey are different.")
        counter += 1

print(f"errors in masking: {counter}")

errors in masking: 0

In [44]:
# Create a new dataframe with just the 'Filled Template' column
aws_prepping = pd.DataFrame(aws_prepping['Filled Template'])

# Display the first few rows of the new dataframe
print(aws_prepping.head())

                                     Filled Template
0  Halie needs help designing a user-friendly che...
1  Draft a letter to Runte, McGlynn and Kautzer e...
2  3. Describe the process of conducting an inter...
3  Can you tell me how companies should handle cu...
4  Write a research proposal for Wolf - Reilly to...

In [45]:
aws_prepping

                                         Filled Template
0      Halie needs help designing a user-friendly che...
1      Draft a letter to Runte, McGlynn and Kautzer e...
2      3. Describe the process of conducting an inter...
3      Can you tell me how companies should handle cu...
4      Write a research proposal for Wolf - Reilly to...
...                                                  ...
42694  Can you write a report on the recent developme...
42695  Can you compile a list of top 10 competitors i...
42696  Please provide a list of the top 5 corporate g...
42697  Can you help me with a workplace culture asses...
42698  During our video conference, can you explain h...

[42699 rows x 1 columns]

In [46]:
aws_prepping["Filled Template"][740]

'Draft a divorce settlement for Jan Dach and Paula Fisher IV, taking into account their joint bank account 11971664.'

In [ ]:
aws_prepping.to_csv("aws_prepping.csv",index=False, header=False)
annotations_df.to_csv("aws_ann_data.csv",index=False)
# Split data into training (first 90%) and testing (last 10%)
total_rows = len(aws_prepping)
split_idx = int(total_rows * 0.9)
training_data = aws_prepping.iloc[:split_idx]
testing_data = aws_prepping.drop(training_data.index)
ann_traning_data = annotations_df[annotations_df["Line"].isin(training_data.index)]
ann_testing_data = annotations_df[annotations_df["Line"].isin(testing_data.index)]



training_data.to_csv("aws_training_data.csv",index=False, header=False)
testing_data.to_csv("aws_testing_data.csv",index=False, header=False)

ann_traning_data.to_csv("aws_ann_training_data.csv",index=False)
ann_testing_data.to_csv("aws_ann_testing_data.csv",index=False)

In [48]:
# First and last line in training data
print("Training Data:")
print(f"First row (index {training_data.index[0]}):")
print(training_data.iloc[0]['Filled Template'])
print("\nLast row (index {training_data.index[-1]}):")
print(training_data.iloc[-1]['Filled Template'])

# First and last line in testing data
print("\nTesting Data:")
print(f"First row (index {testing_data.index[0]}):")
print(testing_data.iloc[0]['Filled Template']) 
print("\nLast row (index {testing_data.index[-1]}):")
print(testing_data.iloc[-1]['Filled Template'])

# Summary statistics
print("\nSummary:")
print(f"Training data shape: {training_data.shape}")
print(f"Testing data shape: {testing_data.shape}")
print(f"Percentage of data in testing set: {testing_data.shape[0]/(training_data.shape[0]+testing_data.shape[0]):.2%}")

Training Data:
First row (index 0):
Halie needs help designing a user-friendly checkout process for their online store.

Last row (index {training_data.index[-1]}):
We should prepare a report on our current compliance status and share it with Vivienne_Quitzon34@hotmail.com to ensure we're on the right track.

Testing Data:
First row (index 38429):
Write a review of the latest neuropsychology textbook for Wolff Group to share with their students at Marielle_Herzog@yahoo.com.

Last row (index {testing_data.index[-1]}):
During our video conference, can you explain how cognitive therapy can help Robert Farrell manage their anger issues?

Summary:
Training data shape: (38429, 1)
Testing data shape: (4270, 1)
Percentage of data in testing set: 10.00%

## AWS Comprehend dataprepping END

In [49]:
from IPython.display import clear_output

for entities in unique_matches:
	regex_pattern = r'\[' + entities + r'\]'
	sextype_examples = df_full[df_full['Template'].str.contains(regex_pattern, na=False)]

	if sextype_examples.empty:
		print("No rows found with the token [SEXTYPE]")
	else:
		num_rows = min(20, len(sextype_examples))
		for i in range(num_rows):
			print("")
			print(sextype_examples[['Template', 'Filled Template']]["Template"].iloc[i])
			print(sextype_examples[['Template', 'Filled Template']]["Filled Template"].iloc[i])
			print("")
			print("="*120)
	#input("Press Enter to load next value...")
	#clear_output(wait=True)

No rows found with the token [SEXTYPE]
No rows found with the token [SEXTYPE]

Please write a research paper on the legal implications of tracking user [IP], [IP], and [USERAGENT] data without consent.
Please write a research paper on the legal implications of tracking user 1751:a95b:05b9:ce8b:431e:ecfe:ce30:bbdd, 21:f7:ae:7f:94:f6, and Mozilla/5.0 (Windows NT 5.0; WOW64; rv:14.3) Gecko/20100101 Firefox/14.3.0 data without consent.

========================================================================================================================

I'm interested in learning more about the privacy implications of collecting [USERAGENT] data. Can you help me out?
I'm interested in learning more about the privacy implications of collecting Opera/11.35 (X11; Linux x86_64; U; VO Presto/2.9.176 Version/12.00) data. Can you help me out?

========================================================================================================================

Could you write a press release about the new ADHD therapy center opening at [LOCATION] [USERAGENT] Street?
Could you write a press release about the new ADHD therapy center opening at 2243 Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_8_9)  AppleWebKit/537.1.0 (KHTML, like Gecko) Chrome/27.0.893.0 Safari/537.1.0 Street?

========================================================================================================================

16. Ensure all necessary software is installed on [NAME] [NAME]'s computer, including the latest [USERAGENT].
16. Ensure all necessary software is installed on Dr. Chester Roberts's computer, including the latest Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.3; Trident/6.0).

========================================================================================================================

Write a research paper on the ethical challenges of using [IP] addresses and [USERAGENT] data in legal cases.
Write a research paper on the ethical challenges of using 129.236.30.80 addresses and Mozilla/5.0 (Windows NT 6.1; WOW64; rv:13.5) Gecko/20100101 Firefox/13.5.6 data in legal cases.

========================================================================================================================

7. Create a checklist for optimizing an eCommerce site's user experience, focusing on [USERAGENT] compatibility.
7. Create a checklist for optimizing an eCommerce site's user experience, focusing on Opera/13.55 (Macintosh; Intel Mac OS X 10.8.4 U; PT Presto/2.9.176 Version/12.00) compatibility.

========================================================================================================================

Please provide a list of the top 5 behavioral therapy apps for [NAME] to try on their [USERAGENT].
Please provide a list of the top 5 behavioral therapy apps for Towne - McClure to try on their Mozilla/5.0 (Windows NT 6.2; Trident/7.0; rv:11.0) like Gecko.

========================================================================================================================

Can you help me develop a questionnaire to assess the impact of screen time on children's cognitive development, especially with the rise in [USERAGENT] usage?
Can you help me develop a questionnaire to assess the impact of screen time on children's cognitive development, especially with the rise in Mozilla/5.0 (Windows; U; Windows NT 6.3)AppleWebKit/535.0.1 (KHTML, like Gecko) Version/6.0.4 Safari/535.0.1 usage?

========================================================================================================================

18. Write a guide for [NAME] [NAME] on how to protect their online privacy, including tips on managing [USERAGENT] settings.
18. Write a guide for Jake Thompson on how to protect their online privacy, including tips on managing Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_10_9 rv:5.0; NB) AppleWebKit/531.1.1 (KHTML, like Gecko) Version/7.1.2 Safari/531.1.1 settings.

========================================================================================================================

I'm interested in how neuropsychology might influence [USERNAME]'s choice of [USERAGENT] when browsing the internet. Can you help?
I'm interested in how neuropsychology might influence Franco.Beatty's choice of Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/531.2.1 (KHTML, like Gecko) Chrome/31.0.812.0 Safari/531.2.1 when browsing the internet. Can you help?

========================================================================================================================

Prepare a social media campaign plan for mental health advocacy, targeting users with specific user agents like [USERAGENT].
Prepare a social media campaign plan for mental health advocacy, targeting users with specific user agents like Opera/10.5 (X11; Linux x86_64; U; FR Presto/2.9.176 Version/10.00).

========================================================================================================================

I'm curious about the relationship between neuropsychology and [USERNAME]'s choice of [USERAGENT] when browsing the web. Can you find some info?
I'm curious about the relationship between neuropsychology and Cary_Toy's choice of Mozilla/5.0 (Windows NT 6.2; WOW64; rv:11.4) Gecko/20100101 Firefox/11.4.8 when browsing the web. Can you find some info?

========================================================================================================================

Please help me create a list of mental health organizations to follow on social media, and I'll check them out using my [USERAGENT] browser.
Please help me create a list of mental health organizations to follow on social media, and I'll check them out using my Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_9_1 rv:4.0; FO) AppleWebKit/533.0.0 (KHTML, like Gecko) Version/4.0.9 Safari/533.0.0 browser.

========================================================================================================================

Hi, can you recommend a mindfulness-based therapy app for my device with [USERAGENT]? Thanks!
Hi, can you recommend a mindfulness-based therapy app for my device with Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.1; .NET CLR 1.1.28332.1)? Thanks!

========================================================================================================================

Write a research paper on the impact of new technology on criminal investigations, such as the use of [USERAGENT] in tracking suspects.
Write a research paper on the impact of new technology on criminal investigations, such as the use of Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_3)  AppleWebKit/535.2.1 (KHTML, like Gecko) Chrome/38.0.843.0 Safari/535.2.1 in tracking suspects.

========================================================================================================================

Could you assist me in writing a report on the challenges faced by human rights activists in the era of [USERAGENT]?
Could you assist me in writing a report on the challenges faced by human rights activists in the era of Opera/9.29 (Macintosh; Intel Mac OS X 10.6.1 U; BS Presto/2.9.164 Version/11.00)?

========================================================================================================================

Write an article about the role of [USERAGENT] information in cyber law investigations for [NAME] to publish on their website.
Write an article about the role of Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_8_7)  AppleWebKit/537.0.2 (KHTML, like Gecko) Chrome/29.0.842.0 Safari/537.0.2 information in cyber law investigations for Carroll - Watsica to publish on their website.

========================================================================================================================

Create a tutorial on using [USERAGENT] for data visualization in business analytics and send it to [EMAIL].
Create a tutorial on using Opera/12.75 (Windows NT 5.1; U; NL Presto/2.9.167 Version/11.00) for data visualization in business analytics and send it to Yasmeen.Collins51@yahoo.com.

========================================================================================================================

I'd love to read an article about how neuropsychology might be involved in [USERNAME]'s preferences for [USERAGENT] while browsing the web.
I'd love to read an article about how neuropsychology might be involved in Travon99's preferences for Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.0; Trident/6.1; .NET CLR 4.4.93858.8) while browsing the web.

========================================================================================================================

3. Track the number of visitors [MASKEDNUMBER] to our eCommerce website using analytics data from [URL] and [USERAGENT].
3. Track the number of visitors 468-497-5143 x202 to our eCommerce website using analytics data from https://moist-evening-wear.info/ and Mozilla/5.0 (Macintosh; PPC Mac OS X 10_10_6 rv:5.0; KG) AppleWebKit/534.2.0 (KHTML, like Gecko) Version/6.0.10 Safari/534.2.0.

========================================================================================================================

Draft a proposal for a harm prevention campaign for [NAME], focusing on securing [EMAIL] and [USERNAME] from potential threats.
Draft a proposal for a harm prevention campaign for Ortiz, Mraz and O'Connell, focusing on securing Herminia89@hotmail.com and Clare16 from potential threats.

========================================================================================================================

Hey, can you provide some case studies of animal cruelty cases and their legal outcomes for [USERNAME]?
Hey, can you provide some case studies of animal cruelty cases and their legal outcomes for Julius_Pollich?

========================================================================================================================

Could you help me create a list of coping strategies for adolescents dealing with stress and anxiety for [USERNAME]?
Could you help me create a list of coping strategies for adolescents dealing with stress and anxiety for Myrtice.Spinka?

========================================================================================================================

Please create a social media post raising awareness about mental health issues that I can share from my account [USERNAME].
Please create a social media post raising awareness about mental health issues that I can share from my account Edyth76.

========================================================================================================================

Prepare a press release for [USERNAME] announcing the launch of a new social responsibility program for underprivileged children in [LOCATION].
Prepare a press release for Brent.Langworth98 announcing the launch of a new social responsibility program for underprivileged children in Buckinghamshire.

========================================================================================================================

Develop a funding proposal for [USERNAME] to support a social responsibility project aimed at reducing homelessness in [LOCATION].
Develop a funding proposal for Lambert2 to support a social responsibility project aimed at reducing homelessness in Buckinghamshire.

========================================================================================================================

Prepare a legal analysis of a recent banking law decision for [USERNAME], focusing on its implications for the industry.
Prepare a legal analysis of a recent banking law decision for Kiel_Kuphal65, focusing on its implications for the industry.

========================================================================================================================

Design a brochure for [USERNAME] to promote their therapy services for individuals with personality disorders.
Design a brochure for Maureen.Armstrong67 to promote their therapy services for individuals with personality disorders.

========================================================================================================================

Would you mind writing a property law FAQ for [USERNAME]? They want to add it to their website.
Would you mind writing a property law FAQ for Bryana.Dibbert-Tremblay? They want to add it to their website.

========================================================================================================================

Create an infographic for [USERNAME] illustrating the impact of different pricing strategies on customer satisfaction in [LOCATION].
Create an infographic for Angeline_Sawayn46 illustrating the impact of different pricing strategies on customer satisfaction in Lueilwitzboro.

========================================================================================================================

Can you write an overview of the various career paths available in forensic psychology for [USERNAME]?
Can you write an overview of the various career paths available in forensic psychology for Cristal_Kuvalis23?

========================================================================================================================

Can you help [USERNAME] understand the importance of having an employment contract?
Can you help Beryl47 understand the importance of having an employment contract?

========================================================================================================================

7. Discuss the use of [USERNAME] as evidence in a cybercrime case.
7. Discuss the use of Ericka_Corwin31 as evidence in a cybercrime case.

========================================================================================================================

Can you create a social media content plan to promote mental health advocacy for [USERNAME]?
Can you create a social media content plan to promote mental health advocacy for Ambrose.Sipes27?

========================================================================================================================

Please explain the legal implications of sharing [USERNAME]'s personal information without their consent during our video conference.
Please explain the legal implications of sharing Dolly28's personal information without their consent during our video conference.

========================================================================================================================

Can you create a list of tips for improving mental health through self-care? I'd like to share it with [USERNAME] at [EMAIL].
Can you create a list of tips for improving mental health through self-care? I'd like to share it with Karianne.Bergnaum98 at Darrion88@yahoo.com.

========================================================================================================================

Would you mind looking into the status of the project's tasks that are assigned to [USERNAME]?
Would you mind looking into the status of the project's tasks that are assigned to Luigi0?

========================================================================================================================

I'm working on a risk assessment for a project, can you provide an example of a risk matrix for [USERNAME]?
I'm working on a risk assessment for a project, can you provide an example of a risk matrix for Ernesto_Jones?

========================================================================================================================

Please write a blog post for [USERNAME] on the importance of understanding social psychology in everyday life.
Please write a blog post for Abigayle66 on the importance of understanding social psychology in everyday life.

========================================================================================================================

Could you create a quiz for [USERNAME] to test their knowledge on forensic psychology and its applications?
Could you create a quiz for Guadalupe_Bartell to test their knowledge on forensic psychology and its applications?

========================================================================================================================

Please explain the maritime law regulations for vessels operating in [LOCATION] and [LOCATION] during our video conference with [NAME] [NAME].
Please explain the maritime law regulations for vessels operating in New Elviefort and Lansing during our video conference with Kerry Daugherty.

========================================================================================================================

7. Identify the top [MASKEDNUMBER] sales channels in [LOCATION] and [LOCATION].
7. Identify the top 1-913-315-0557 sales channels in Deonteburgh and Lake Lunacester.

========================================================================================================================

Draft an email to [NAME] at [EMAIL] discussing the process of dividing marital assets in a divorce case in [LOCATION].
Draft an email to VonRueden LLC at Jacquelyn51@yahoo.com discussing the process of dividing marital assets in a divorce case in Indiana.

========================================================================================================================

What are the requirements for [NAME] [NAME] to apply for permanent residency in [LOCATION]?
What are the requirements for Susie Bergnaum to apply for permanent residency in West Kelleyburgh?

========================================================================================================================

Create a personal injury claim form for [NAME] [NAME] who was injured at [LOCATION] in [LOCATION].
Create a personal injury claim form for Clinton Kohler DVM who was injured at 3124 Felton Track in Port Skyeworth.

========================================================================================================================

I'm looking for information on the permits required for a home renovation at [LOCATION] [NAME] Street. Can you help me find that?
I'm looking for information on the permits required for a home renovation at 6653 Sipes, Schuster and Watsica Street. Can you help me find that?

========================================================================================================================

11. Analyze the capacity planning strategy for [NAME] [NAME]'s manufacturing facility in [LOCATION].
11. Analyze the capacity planning strategy for Pat Zboncak's manufacturing facility in Youngstown.

========================================================================================================================

Could you provide [NAME] [NAME] with a list of the most common violations of securities law in [LOCATION]?
Could you provide Jean Watsica with a list of the most common violations of securities law in Alabama?

========================================================================================================================

What are the consequences of overstaying a visa for [NAME] [NAME] who is currently living in [LOCATION]?
What are the consequences of overstaying a visa for Margie Douglas who is currently living in Lake Claudinefort?

========================================================================================================================

Can you discuss the zoning regulations for [NAME] [NAME]'s property located at [LOCATION] in [LOCATION] during our video conference?
Can you discuss the zoning regulations for Minnie Abbott's property located at 40464 Maida Lock in Kylaborough during our video conference?

========================================================================================================================

What factors should [NAME] consider when choosing a personal injury lawyer in [LOCATION]?
What factors should Paucek Group consider when choosing a personal injury lawyer in Halvorsonfield?


# Short form removal

In [50]:
# contraction expansion

def remove_short_form(text):
    if isinstance(text, str):
        contractions = {
            # Common negatives
            "isn't": "is not",
            "wasn't": "was not",
            "weren't": "were not",
            "haven't": "have not",
            "hasn't": "has not",
            "hadn't": "had not",
            "don't": "do not",
            "doesn't": "does not",
            "didn't": "did not",
            "won't": "will not",
            "wouldn't": "would not",
            "shouldn't": "should not",
            "couldn't": "could not",
            "mustn't": "must not",
            "shan't": "shall not",
            
            # Pronoun contractions
            "i'm": "i am",
            "you're": "you are",
            "he's": "he is",
            "she's": "she is",
            "it's": "it is",
            "we're": "we are",
            "they're": "they are",

            # Possession / descriptive
            "who's": "who is",
            "what's": "what is",
            "where's": "where is",
            "when's": "when is",
            "why's": "why is",
            "how's": "how is",
            "there's": "there is",
            "here's": "here is",
            "that's": "that is",

            # Past and hypothetical
            "i'd": "i would",
            "you'd": "you would",
            "he'd": "he would",
            "she'd": "she would",
            "we'd": "we would",
            "they'd": "they would",

            # Future forms
            "i'll": "i will",
            "you'll": "you will",
            "he'll": "he will",
            "she'll": "she will",
            "it'll": "it will",
            "we'll": "we will",
            "they'll": "they will",

            # Perfect tense
            "i've": "i have",
            "you've": "you have",
            "we've": "we have",
            "they've": "they have",
            "he's": "he has",
            "she's": "she has",
            "it's": "it has",

            # Imperative/other
            "let's": "let us",
            "y'all": "you all",
            "o'clock": "of the clock",
            "ma'am": "madam",
            "gonna": "going to",
            "wanna": "want to",
            "gotta": "got to",
            "ain't": "is not"
        }

        # Replace contractions case-insensitively
        for contraction, replacement in contractions.items():
            text = re.sub(rf"\b{re.escape(contraction)}\b", replacement, text, flags=re.IGNORECASE)

        return text
    return text

# Normalization

In [51]:
def normalize_text(text):
	# text to lower
	parts = re.split(r'(\[[^\]]*\])', text)

	processed_parts = []
	for segment in parts:
		if segment.startswith('[') and segment.endswith(']'):
			processed_parts.append(segment)
		else:
			processed_parts.append(segment.lower())

	text = "".join(processed_parts)
	# remove extra spaces
	text = re.sub(r'\s+', ' ', text)
	# Use the function to remove short forms
	text = remove_short_form(text)
	return text

In [52]:
from tqdm import tqdm

tqdm.pandas(desc="Normalizing Template")
df_full['Template'] = df_full['Template'].progress_apply(normalize_text)
tqdm.pandas(desc="Normalizing Filled Template")
df_full['Filled Template'] = df_full['Filled Template'].progress_apply(normalize_text)

Normalizing Template: 100%|██████████| 42699/42699 [00:07<00:00, 5538.94it/s]
Normalizing Filled Template: 100%|██████████| 42699/42699 [00:07<00:00, 5383.98it/s]

# Lemming

In [53]:

# Load the English NLP model
nlp = spacy.load("en_core_web_sm")# TODO: Make this use the large model
spacy.prefer_gpu()

def lemmatize_text(text):
    # Check for missing values
    if pd.isna(text):
        return text
    # Process the text with spaCy
    doc = nlp(text)
    # Join lemmatized tokens back into a string
    return " ".join(token.lemma_ for token in doc)

In [54]:

try:
	# Try loading the lemmatized data
	df_full = pd.read_csv("lemmatized_data.csv")
	print("Loaded data from lemmatized_data.csv")
except FileNotFoundError:
	# If the file doesn't exist, perform lemmatization
	print("lemmatized_data.csv not found, performing lemmatization...")
	tqdm.pandas(desc="Lemmatizing Template")
	df_full['Template'] = df_full['Template'].progress_apply(lemmatize_text)
	tqdm.pandas(desc="Lemmatizing Filled Template")
	df_full['Filled Template'] = df_full['Filled Template'].progress_apply(lemmatize_text)

	# Check the results
	print(df_full.head())
	#save
	df_full.to_csv("lemmatized_data.csv", index=False)

Loaded data from lemmatized_data.csv

In [55]:
# Count the labeled items in the DataFrame
total_labeled_items = count_labeled_items(df_full)
print(f"Total number of labeled items: {total_labeled_items}")

Total number of labeled items: 83834

# Sentences Splitting

In [56]:
def split_into_sentences(text):
    """
    Splits a given text (string) into a list of sentences using spaCy's sentence segmentation.
    Returns an empty list if the input is None or NaN.
    """
    if pd.isna(text):
        return []
    doc = nlp(text)
    return [sent.text.strip() for sent in doc.sents if sent.text.strip()]

In [57]:
import os

if not os.path.exists("sentences_data.csv"):
	tqdm.pandas(desc="Splitting Sentences")
	
	df_full["Template_Sentences"] = df_full["Template"].progress_apply(split_into_sentences)
	df_full["Filled_Sentences"]   = df_full["Filled Template"].progress_apply(split_into_sentences)
	
	# Optionally, save the updated dataframe
	df_full.to_csv("sentence_data.csv", index=False)
	
	print("Sentence splitting complete. Data saved to sentence_data.csv")
	print(df_full.head())
else:
	print("sentence_data.csv already exists. Skipping sentence splitting.")

Splitting Sentences: 100%|██████████| 42699/42699 [07:09<00:00, 99.52it/s]
Splitting Sentences: 100%|██████████| 42699/42699 [06:21<00:00, 111.86it/s]

Sentence splitting complete. Data saved to sentence_data.csv
                                            Template  \
0  in our video conference , discuss the role of ...
1  could you draft a letter for [ name ] to send ...
2  discuss the option for [ name ] [ name ] who w...
3  13 . write a press release announce [ name ] [...
4  9 . develop an inventory management plan for [...

                                     Filled Template  \
0  in our video conference , discuss the role of ...
1  could you draft a letter for dietrich , schuli...
2  discuss the option for jeffery pfeffer who wan...
3  13 . write a press release announce gayle wate...
4  9 . develop an inventory management plan for e...

                                  Template_Sentences  \
0  [in our video conference , discuss the role of...
1  [could you draft a letter for [ name ] to send...
2  [discuss the option for [ name ] [ name ] who ...
3  [13 ., write a press release announce [ name ]...
4  [9 . develop an inventory management plan for ...

                                    Filled_Sentences
0  [in our video conference , discuss the role of...
1  [could you draft a letter for dietrich , schul...
2  [discuss the option for jeffery pfeffer who wa...
3  [13 ., write a press release announce gayle wa...
4  [9 . develop an inventory management plan for ...

## VIEW DATA

In [58]:
df_full.head()

,Template,Filled Template,Template_Sentences,Filled_Sentences
0,"in our video conference , discuss the role of ...","in our video conference , discuss the role of ...","[in our video conference , discuss the role of...","[in our video conference , discuss the role of..."
1,could you draft a letter for [ name ] to send ...,"could you draft a letter for dietrich , schuli...",[could you draft a letter for [ name ] to send...,"[could you draft a letter for dietrich , schul..."
2,discuss the option for [ name ] [ name ] who w...,discuss the option for jeffery pfeffer who wan...,[discuss the option for [ name ] [ name ] who ...,[discuss the option for jeffery pfeffer who wa...
3,13 . write a press release announce [ name ] [...,13 . write a press release announce gayle wate...,"[13 ., write a press release announce [ name ]...","[13 ., write a press release announce gayle wa..."
4,9 . develop an inventory management plan for [...,9 . develop an inventory management plan for e...,[9 . develop an inventory management plan for ...,[9 . develop an inventory management plan for ...

In [59]:
from IPython.display import clear_output

for entities in unique_matches:
	print(entities)

	entities = entities.lower()
	print(entities)
	regex_pattern = r'\[ ' + entities + r' \]'
	sextype_examples = df_full[df_full['Template'].str.contains(regex_pattern, na=False)]

	if sextype_examples.empty:
		print("No rows found with the token")
	else:
		num_rows = min(20, len(sextype_examples))
		for i in range(num_rows):
			print("")
			print(sextype_examples[['Template', 'Filled Template']]["Template"].iloc[i])
			print(sextype_examples[['Template', 'Filled Template']]["Filled Template"].iloc[i])
			print("")
			print("="*120)
	#input("Press Enter to load next value...")
	#clear_output(wait=True)

ETHEREUMADDRESS
ethereumaddress
No rows found with the token
LITECOINADDRESS
litecoinaddress
No rows found with the token
USERAGENT
useragent

12 . monitor the website 's loading speed and optimize it by analyze datum from [ useragent ] and [ IP ] .
12 . monitor the website 's loading speed and optimize it by analyze datum from mozilla/5.0 ( macintosh ; ppc mac os x 10_6_9 rv:3.0 ; hi ) applewebkit/536.0.0 ( khtml , like gecko ) version/4.0.6 safari/536.0.0 and fb65 : fec4 : bc09:1108 : cb0d : ff05:9da6 : cfa7 .

========================================================================================================================

how can I ensure that I be follow privacy law when deal with [ URL ] and [ useragent ] information ?
how can I ensure that I be follow privacy law when deal with https://dry-steam.com/ and mozilla/5.0 ( compatible ; msie 7.0 ; window not 5.2 ; trident/5.0 ; .net clr 1.7.22860.9 ) information ?

========================================================================================================================

I be interested in learn more about the privacy implication of collect [ useragent ] datum . can you help I out ?
I be interested in learn more about the privacy implication of collect opera/11.35 ( x11 ; linux x86_64 ; u ; vo presto/2.9.176 version/12.00 ) datum . can you help I out ?

========================================================================================================================

I be interested in how neuropsychology might influence [ USERNAME ] 's choice of [ useragent ] when browse the internet . can you help ?
I be interested in how neuropsychology might influence franco.beatty 's choice of mozilla/5.0 ( window ; u ; window not 5.0 ) applewebkit/531.2.1 ( khtml , like gecko ) chrome/31.0.812.0 safari/531.2.1 when browse the internet . can you help ?

========================================================================================================================

can you write a blog post discuss the ethical consideration of use [ URL ] and [ useragent ] datum in legal proceeding ?
can you write a blog post discuss the ethical consideration of use https://all-c-clamp.biz/ and mozilla/5.0 ( x11 ; linux x86_64 applewebkit/536.1.1 ( khtml , like gecko ) chrome/33.0.802.0 safari/536.1.1 datum in legal proceeding ?

========================================================================================================================

prepare a social media campaign plan for mental health advocacy , target user with specific user agent like [ useragent ] .
prepare a social media campaign plan for mental health advocacy , target user with specific user agent like opera/10.5 ( x11 ; linux x86_64 ; u ; fr presto/2.9.176 version/10.00 ) .

========================================================================================================================

create an infographic for personal loan account illustrate the stage of change management and the role of [ useragent ] in the process .
create an infographic for personal loan account illustrate the stage of change management and the role of mozilla/5.0 ( compatible ; msie 7.0 ; window not 6.1 ; trident/5.1 ) in the process .

========================================================================================================================

can you come up with a mental health awareness hashtag for our social medium campaign ? we would like to track its performance use [ useragent ] .
can you come up with a mental health awareness hashtag for our social medium campaign ? we would like to track its performance use mozilla/5.0 ( macintosh ; ppc mac os x 10_10_4 rv:3.0 ; nb ) applewebkit/533.2.1 ( khtml , like gecko ) version/6.1.10 safari/533.2.1 .

========================================================================================================================

please write a research paper on the legal implication of track user [ IP ] , [ IP ] , and [ useragent ] datum without consent .
please write a research paper on the legal implication of track user 1751 : a95b:05b9 : ce8b:431e : ecfe : ce30 : bbdd , 21 : f7 : ae:7f:94 : f6 , and mozilla/5.0 ( window not 5.0 ; wow64 ; rv:14.3 ) gecko/20100101 firefox/14.3.0 datum without consent .

========================================================================================================================

3 . track the number of visitor [ MASKEDNUMBER ] to our ecommerce website use analytic datum from [ URL ] and [ useragent ] .
3 . track the number of visitor 468 - 497 - 5143 x202 to our ecommerce website use analytic datum from https://moist-evening-wear.info/ and mozilla/5.0 ( macintosh ; ppc mac os x 10_10_6 rv:5.0 ; kg ) applewebkit/534.2.0 ( khtml , like gecko ) version/6.0.10 safari/534.2.0 .

========================================================================================================================

14 . write a white paper on the future of ecommerce , with a focus on emerge technology such as [ useragent ] and [ IP ] .
14 . write a white paper on the future of ecommerce , with a focus on emerge technology such as mozilla/5.0 ( compatible ; msie 7.0 ; window not 6.3 ; trident/5.1 ; .net clr 1.7.57508.9 ) and efba : eb09:2daa:2cf6:77f1 : b5ba : caea : c4d5 .

========================================================================================================================

11 . develop a strategy for [ name ] to engage with their online community , focus on platform with user agent like [ useragent ] .
11 . develop a strategy for yost - hilll to engage with their online community , focus on platform with user agent like mozilla/5.0 ( window ; u ; window not 6.0)applewebkit/531.1.1 ( khtml , like gecko ) version/6.0.1 safari/531.1.1 .

========================================================================================================================

create a comprehensive guide on the legal aspect of protect [ useragent ] and [ URL ] datum from unauthorized access .
create a comprehensive guide on the legal aspect of protect opera/12.77 ( macintosh ; intel mac os x 10.10.5 u ; be presto/2.9.160 version/12.00 ) and https://brilliant-commotion.net datum from unauthorized access .

========================================================================================================================

create a list of good practice for secure online account , include advice on [ password ] and [ useragent ] management .
create a list of good practice for secure online account , include advice on hhvqrs2t2aob and mozilla/5.0 ( macintosh ; intel mac os x 10_8_5 ) applewebkit/534.0.0 ( khtml , like gecko ) chrome/36.0.839.0 safari/534.0.0 management .

========================================================================================================================

hey , I be work on a case study about privacy right and [ useragent ] surveillance . can you help I find relevant source ?
hey , I be work on a case study about privacy right and mozilla/5.0 ( macintosh ; intel mac os x 10_8_2 rv:5.0 ; bo ) applewebkit/531.1.0 ( khtml , like gecko ) version/5.0.7 safari/531.1.0 surveillance . can you help I find relevant source ?

========================================================================================================================

I be curious about how constitutional law address the use of personal datum , like [ URL ] and [ useragent ] , in the digital age .
I be curious about how constitutional law address the use of personal datum , like https://automatic-gasoline.com and mozilla/5.0 ( macintosh ; u ; intel mac os x 10_5_9 ) applewebkit/538.0.2 ( khtml , like gecko ) chrome/39.0.873.0 safari/538.0.2 , in the digital age .

========================================================================================================================

yo , I be curious about the regulation around use [ IP ] and [ useragent ] datum for targeted advertising . can you help ?
yo , I be curious about the regulation around use 106.9.44.55 and mozilla/5.0 ( window ; u ; window not 5.2)applewebkit/534.2.1 ( khtml , like gecko ) version/5.0.3 safari/534.2.1 datum for targeted advertising . can you help ?

========================================================================================================================

I be work on a project about human right in the digital age . can you help I analyze the impact of [ useragent ] on freedom of expression ?
I be work on a project about human right in the digital age . can you help I analyze the impact of mozilla/5.0 ( window ; u ; window not 6.1)applewebkit/534.2.0 ( khtml , like gecko ) version/4.1.1 safari/534.2.0 on freedom of expression ?

========================================================================================================================

hi ! I be look for a mindfulness - base therapy app for [ useragent ] . can you find one for I ?
hi ! I be look for a mindfulness - base therapy app for mozilla/5.0 ( x11 ; linux i686 applewebkit/538.1.2 ( khtml , like gecko ) chrome/23.0.813.0 safari/538.1.2 . can you find one for I ?

========================================================================================================================

8 . analyze the online presence of [ name ] 's competitor , include their website design , social medium engagement , and [ useragent ] datum .
8 . analyze the online presence of metz and son 's competitor , include their website design , social medium engagement , and mozilla/5.0 ( macintosh ; intel mac os x 10_9_0 ) applewebkit/534.1.0 ( khtml , like gecko ) chrome/31.0.864.0 safari/534.1.0 datum .

========================================================================================================================
USERNAME
username
No rows found with the token
LOCATION
location

could you draft a letter for [ name ] to send to their insurance company regard a claim dispute under [ location ] law ?
could you draft a letter for dietrich , schulist and romaguera to send to their insurance company regard a claim dispute under washington law ?

========================================================================================================================

discuss the option for [ name ] [ name ] who want to obtain a green card through employment in [ location ] .
discuss the option for jeffery pfeffer who want to obtain a green card through employment in port ron .

========================================================================================================================

13 . write a press release announce [ name ] [ name ] 's new mindfulness - base therapy practice in [ location ] .
13 . write a press release announce gayle water 's new mindfulness - base therapy practice in oceanside .

========================================================================================================================

during the video conference with [ name ] [ name ] , discuss strategy to optimize inventory turnover and minimize stockout at their [ location ] store .
during the video conference with miss elsa hermiston dvm , discuss strategy to optimize inventory turnover and minimize stockout at their bechtelarberg store .

========================================================================================================================

please develop a survey for [ name ] to assess the impact of industrial - organizational psychology intervention on employee well - being at [ location ] [ location ] .
please develop a survey for heller - dibbert to assess the impact of industrial - organizational psychology intervention on employee well - being at 578 casimer passage .

========================================================================================================================

what be the difference between first - generation and second - generation antipsychotic for resident of [ location ] ?
what be the difference between first - generation and second - generation antipsychotic for resident of 76511 ?

========================================================================================================================

hey , can you help I understand the step to appeal an administrative law decision in [ location ] ?
hey , can you help I understand the step to appeal an administrative law decision in west virginia ?

========================================================================================================================

create a list of mental health support organization in [ location ] and [ location ] for [ name ] [ name ] to share with their network .
create a list of mental health support organization in lake pedroberg and bernardchester for jessie witting to share with their network .

========================================================================================================================

please create a legal analysis of the sport bet law in [ location ] and send it to [ email ] .
please create a legal analysis of the sport bet law in montana and send it to nichole.kulas96@gmail.com .

========================================================================================================================

18 . provide an overview of the positive psychology conference take place in [ location ] and [ location ] .
18 . provide an overview of the positive psychology conference take place in hardyburgh and lynchside .

========================================================================================================================

can you write a memo on compliance with labor law for a company operate in [ location ] ? please send it to [ email ] .
can you write a memo on compliance with labor law for a company operate in florida ? please send it to raegan_heathcote57@yahoo.com .

========================================================================================================================

develop a comprehensive questionnaire for [ name ] to collect datum on the adoption of legal technology by law firm in [ location ] .
develop a comprehensive questionnaire for runolfsson , nitzsche and quitzon to collect datum on the adoption of legal technology by law firm in sengerton .

========================================================================================================================

create a list of eco - friendly office supply for [ name ] [ name ] to consider purchase for their company in [ location ] .
create a list of eco - friendly office supply for miss amelia macgyver to consider purchase for their company in crookstown .

========================================================================================================================

hey , [ name ] , can you send I an article on animal right law in [ location ] ?
hey , micaela , can you send I an article on animal right law in hahnside ?

========================================================================================================================

create an educational presentation on psychopharmacology for [ name ] 's upcoming lecture at the [ location ] [ LOCATION ] facility .
create an educational presentation on psychopharmacology for schulist , jaskolski and nolan 's upcoming lecture at the 932 colt crescent facility .

========================================================================================================================

write a research paper on the role of the judiciary in interpret the constitution in [ location ] for [ email ] .
write a research paper on the role of the judiciary in interpret the constitution in texas for jaeden95@hotmail.com .

========================================================================================================================

create a list of resource on civil right law for [ name ] to use in their upcoming seminar in [ location ] .
create a list of resource on civil right law for gibson , pouros and gutmann to use in their upcoming seminar in flint .

========================================================================================================================

8 . draft a press release for [ name ] [ name ] announce their mental health advocacy event in [ location ] .
8 . draft a press release for dave kassulke announce their mental health advocacy event in barrowsburgh .

========================================================================================================================

hey , can you analyze the impact of brexit on the supply chain of company operate in [ location ] ?
hey , can you analyze the impact of brexit on the supply chain of company operate in dietrichboro ?

========================================================================================================================

prepare a list of mental health professional available in [ location ] for [ name ] [ name ] to consult during a crisis intervention .
prepare a list of mental health professional available in avaboro for bennie grime to consult during a crisis intervention .

========================================================================================================================
MASKEDNUMBER
maskednumber

please provide a list of change management good practice for check account to implement during their upcoming [ maskednumber ] project .
please provide a list of change management good practice for check account to implement during their upcoming ( 434 ) 558 - 6344 x0929 project .

========================================================================================================================

8 . project sale for the [ email ] marketing campaign : [ maskednumber ] pound sterling .
8 . project sale for the marcella33@gmail.com marketing campaign : 733.50 pound sterling .

========================================================================================================================

I need a report on the inventory management of [ name ] 's business , track their [ maskednumber ] product .
I need a report on the inventory management of matilde 's business , track their 699 - 548 - 4500 x326 product .

========================================================================================================================

please create a vendor management policy for [ name ] to implement in their organization , include guideline on personal loan account and [ maskednumber ] usage .
please create a vendor management policy for oberbrunner - kshlerin to implement in their organization , include guideline on personal loan account and 18973550 usage .

========================================================================================================================

please provide a summary of the ethical guideline for legal professional when handle client ' credit card account and [ maskednumber ] information .
please provide a summary of the ethical guideline for legal professional when handle client ' credit card account and 14545783 information .

========================================================================================================================

can you help [ name ] create a pricing strategy for their product ? they have get [ maskednumber ] item in their catalog .
can you help huel , king and schimmel create a pricing strategy for their product ? they have get 675 - 799 - 1388 x128 item in their catalog .

========================================================================================================================

please create a presentation on the jurisdiction of military court for [ maskednumber ] type of offense for [ name ] .
please create a presentation on the jurisdiction of military court for ( 662 ) 953 - 0910 x9652 type of offense for kuhlman - welch .

========================================================================================================================

I need some help with sale forecasting for [ maskednumber ] product , can you give I a hand ?

In [60]:
# Define a dataset class to store our data splits
class dataset:
    def __init__(self, name, dataset, training_data=None, testing_data=None):
        self.name = name
        self.dataset = dataset
        self.training_data = training_data
        self.testing_data = testing_data
        self.text_accuracy = 0
        self.precision = 0
        self.recall = 0
        self.f1 = 0
        self.nlp = None
    
    def __str__(self):
        return f"Dataset {self.name}: {len(self.dataset)} total rows, {len(self.training_data)} training, {len(self.testing_data)} testing"

# Create a single dataset with 100% of the data
test_pct = 1  # 100% of the data

split_index = int(len(df_full) * 0.9)

# Split the dataset into training (90%) and testing (10%)
training_data = df_full[:split_index]
testing_data = df_full[split_index:]

# Create a dataset instance with the splits
result = dataset(
    name=test_pct, 
    dataset=df_full, 
    training_data=training_data, 
    testing_data=testing_data
)

# Store in datasets dictionary if needed
datasets = {test_pct: result}

print(f"Total dataset size: {len(df_full)}")
print(f"Training set size: {len(training_data)} ({len(training_data)/len(df_full):.1%})")
print(f"Test set size: {len(testing_data)} ({len(testing_data)/len(df_full):.1%})")

# Save the datasets to disk
training_data.to_csv("training_data.csv", index=False)
testing_data.to_csv("test_data.csv", index=False)

Total dataset size: 42699
Training set size: 38429 (90.0%)
Test set size: 4270 (10.0%)

### NLP Implementation

In [61]:
analyzer = AnalyzerEngine()

In [62]:
# test Call analyzer to get results
results = analyzer.analyze(text="My phone number is 212-555-5555",
                           entities=["PHONE_NUMBER"],
                           language='en')
print(results)

[type: PHONE_NUMBER, start: 19, end: 31, score: 0.75]

In [63]:
def clean_text(text):
    """Clean and normalize text."""
    return str(text).strip()

def extract_entities(template, filled):
    """
    Extract entities by aligning placeholders (e.g. "[NAME_1]" => "NAME")
    with the actual text that replaced them in `filled`.
    """
    entities = []
    i = 0  # pointer into template
    j = 0  # pointer into filled

    while i < len(template) and j < len(filled):
        if template[i] == '[':
            # Found a placeholder
            closing = template.find(']', i)
            if closing == -1:
                break  # malformed placeholder; exit
            placeholder = template[i+1:closing]  # e.g. "NAME_1"
            label = re.sub(r'_\d+', '', placeholder)  # becomes "NAME"

            next_i = closing + 1
            # Look for next bracket to capture literal text that follows the placeholder
            next_bracket = template.find('[', next_i)
            literal = template[next_i:] if next_bracket == -1 else template[next_i:next_bracket]

            if literal:
                literal_index = filled.find(literal, j)
                if literal_index == -1:
                    # If literal is missing, log a warning and skip this placeholder
                    print(f"WARNING: Could not find literal '{literal}' after placeholder '{label}'. Skipping.")
                    i = closing + 1
                    continue
                else:
                    entity_start = j
                    entity_end = literal_index
                    j = literal_index  # advance pointer j to the literal start
            else:
                # No literal after the placeholder; log info and skip
                print(f"INFO: No literal after placeholder '[{placeholder}]'. Skipping.")
                i = closing + 1
                continue

            entities.append((entity_start, entity_end, label))
            i = closing + 1
        else:
            if template[i] == filled[j]:
                i += 1
                j += 1
            else:
                j += 1

    return entities

In [ ]:
def NLP_training(df_training, df_testing):
    """
    Train an NER model using df_training and evaluate using df_testing.
    Returns text accuracy, label-level precision, recall, F1 score, 
    detailed error counts, and the trained nlp model.
    """
    import random
    import spacy
    from spacy.training.example import Example
    from spacy.util import minibatch
    
    # ------------------------------
    # Step 0: Build and Clean Training Data
    # ------------------------------
    raw_train_data = []
    for _, row in df_training.iterrows():
        template = clean_text(row['Template'])
        filled = clean_text(row['Filled Template'])
        entities = extract_entities(template, filled)
        if entities:
            raw_train_data.append((filled, {"entities": entities}))
    
    # ------------------------------
    # Step 0.5: Re-align Entity Offsets to Token Boundaries
    # ------------------------------
    tokenizer_nlp = spacy.blank("en")
    aligned_train_data = []
    for text, annotation in raw_train_data:
        doc = tokenizer_nlp(text)
        new_entities = []
        for start, end, label in annotation["entities"]:
            # Expand to token boundaries.
            span = doc.char_span(start, end, alignment_mode="expand")
            if span is not None:
                new_entities.append((span.start_char, span.end_char, label))
            else:
                print(f"WARNING: Could not align entity '{text[start:end]}' in text: {text}")
        if new_entities:
            aligned_train_data.append((text, {"entities": new_entities}))
    
    TRAIN_DATA = aligned_train_data
    
    # ------------------------------
    # Step 1: Optionally shuffle or further split training data if needed
    # ------------------------------
    # For now, we assume df_training is fully for training, and df_testing will be used for evaluation.
    
    # ------------------------------
    # Step 2: Create and Configure the Model
    # ------------------------------
    nlp = spacy.blank("en")
    if "ner" not in nlp.pipe_names:
        ner = nlp.add_pipe("ner", last=True)
    else:
        ner = nlp.get_pipe("ner")
    
    # Add labels from training data.
    for _, annotations in TRAIN_DATA:
        for _, _, label in annotations["entities"]:
            ner.add_label(label)
    
    # ------------------------------
    # Step 3: Train the Model Using Batches with Dropout
    # ------------------------------
    optimizer = nlp.begin_training()
    n_iter = 20  # Number of epochs
    batch_size = 16
    for itn in range(n_iter):
        random.shuffle(TRAIN_DATA)
        batches = minibatch(TRAIN_DATA, size=batch_size)
        losses = {}
        for batch in batches:
            examples = []
            for text, annotations in batch:
                doc = nlp.make_doc(text)
                examples.append(Example.from_dict(doc, annotations))
            nlp.update(examples, sgd=optimizer, drop=0.3, losses=losses)
        print(f"Iteration {itn + 1}/{n_iter} - Losses: {losses}")
    
    # ------------------------------
    # Step 4: Evaluate on df_testing with Detailed Metrics
    # ------------------------------
    total_texts = 0
    text_correct_count = 0
    TP = 0  # true positives for individual entity predictions
    FP = 0  # false positives: entities predicted but not in ground truth
    FN = 0  # false negatives: ground truth entities not predicted
    failed_entities = []  # collect details on mismatches
    
    for _, row in df_testing.iterrows():
        text = clean_text(row['Filled Template'])
        # Extract ground truth entities from the provided template/fill pair.
        template = clean_text(row['Template'])
        ground_entities = extract_entities(template, text)
        # Align ground truth entities to token boundaries.
        doc = nlp.make_doc(text)
        aligned_ground = []
        for start, end, label in ground_entities:
            span = doc.char_span(start, end, alignment_mode="expand")
            if span is not None:
                aligned_ground.append((span.start_char, span.end_char, label))
            else:
                print(f"WARNING: Could not align ground truth entity '{text[start:end]}'")
        # Get predicted entities from the model.
        pred_doc = nlp(text)
        predicted = [(ent.start_char, ent.end_char, ent.label_) for ent in pred_doc.ents]
        
        # Text-level evaluation: exact match of entity sets.
        if set(predicted) == set(aligned_ground):
            text_correct_count += 1
        
        # Label-level evaluation.
        for entity in aligned_ground:
            total_texts += 0  # placeholder if needed; not used in label-level metrics
            if entity in predicted:
                TP += 1
            else:
                FN += 1
                failed_entities.append({"expected": entity, "text": text})
        for entity in predicted:
            if entity not in aligned_ground:
                FP += 1
        
        total_texts += 1
    
    # Compute text-level accuracy.
    text_accuracy = text_correct_count / total_texts if total_texts > 0 else 0
    
    # Compute precision, recall and F1 for entity-level predictions.
    precision = TP / (TP + FP) if (TP + FP) > 0 else 0
    recall = TP / (TP + FN) if (TP + FN) > 0 else 0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
    
    print("\n=== Evaluation on Testing Data ===")
    print(f"Text Accuracy (exact match): {text_accuracy:.2%}")
    print(f"Entity-level Precision: {precision:.2%}")
    print(f"Entity-level Recall: {recall:.2%}")
    print(f"Entity-level F1 Score: {f1:.2%}")
    print(f"False Positives: {FP}")
    print(f"False Negatives: {FN}")
    
    return text_accuracy, precision, recall, f1, {"FP": FP, "FN": FN, "failed_entities": failed_entities}, nlp

def mask_pii(text, model):
        """
        Mask detected entities in the text with their label names.
        Entities are replaced from the end of the text to avoid offset issues.
        """
        doc = model(text)
        spans = [(ent.start_char, ent.end_char, ent.label_) for ent in doc.ents]
        spans = sorted(spans, key=lambda x: x[0], reverse=True)
        masked_text = text
        for start, end, label in spans:
            masked_text = masked_text[:start] + f"[{label}]" + masked_text[end:]
        return masked_text

In [65]:
for key, ds_obj in datasets.items():
    print(f"Processing dataset with test percentage: {ds_obj.name}")
    # ds_obj.dataset_training and ds_obj.dataset_testing should be defined in each dataset object.
    text_acc, precision, recall, f1, error_details, nlp_model = NLP_training(ds_obj.training_data, ds_obj.testing_data)
    ds_obj.text_accuracy = text_acc
    ds_obj.precision = precision
    ds_obj.recall = recall
    ds_obj.f1 = f1
    ds_obj.nlp = nlp_model
    print(ds_obj)

Processing dataset with test percentage: 1
WARNING: Could not find literal ' , can you share the google analytic datum for our ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' . think you might be interested in attend .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' be startup in the tech industry , focus on market analysis and financial projection .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' 's team in the ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' be check account and ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' . can you write one ?' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' 's financial blog about the importance of update estate plan regularly .' after placeholder ' name '. Skipping.
WARNING: Could not find literal '-focuse campaign .' after placeholder ' job'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' . can you help I find one ?' after placeholder ' URL '. Skipping.
WARNING: Could not find literal '-inclusive curriculum for school in ' after placeholder ' gender'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' school .' after placeholder ' LOCATION '. Skipping.
WARNING: Could not find literal 's in family therapy session .' after placeholder ' job'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal '-based team ?' after placeholder ' location'. Skipping.
WARNING: Could not find literal ' . can you read it and let I know your thought ?' after placeholder ' url '. Skipping.
WARNING: Could not find literal ' and the expect market penetration rate ' after placeholder ' MASKEDNUMBER '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' improve customer experience design in their ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' be in the ' after placeholder ' name '. Skipping.
WARNING: Could not find literal 's in the company ?' after placeholder ' job'. Skipping.
WARNING: Could not find literal 's ? email it to ' after placeholder ' job'. Skipping.
WARNING: Could not find literal '-based company .' after placeholder ' location'. Skipping.
WARNING: Could not find literal '-time dui conviction in ' after placeholder ' maskednumber'. Skipping.
WARNING: Could not find literal '-based store .' after placeholder ' location'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal '-based company , can you write a report on that ?' after placeholder ' location'. Skipping.
WARNING: Could not find literal ' be last ' after placeholder ' name '. Skipping.
WARNING: Could not find literal '-word company description .' after placeholder ' MASKEDNUMBER'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' be in the ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' manufacturing plant .' after placeholder ' location '. Skipping.
WARNING: Could not find literal ' invite ' after placeholder ' email '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal '-based business .' after placeholder ' location'. Skipping.
WARNING: Could not find literal ' involve the disputed ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
INFO: No literal after placeholder '[ url ]'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' need help understand voter suppression law in ' after placeholder ' name '. Skipping.
WARNING: Could not find literal '-related disorder . can you find some information on that ?' after placeholder ' job'. Skipping.
INFO: No literal after placeholder '[ url ]'. Skipping.
WARNING: Could not find literal ' 's ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' on the implication of a recent civil right rule in ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' advocate for strong animal protection law in ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' 's startup .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal 's to improve their professional skill . can you help ?' after placeholder ' job'. Skipping.
WARNING: Could not find literal '-based store .' after placeholder ' location'. Skipping.
WARNING: Could not find literal '-based business .' after placeholder ' location'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal 's in the ' after placeholder ' job'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal '-based office .' after placeholder ' location'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' with ' after placeholder ' location '. Skipping.
INFO: No literal after placeholder '[ url ]'. Skipping.
WARNING: Could not find literal ' kenyan shill into several project .' after placeholder ' MASKEDNUMBER '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' netherland antillian guilder at an interest rate of ' after placeholder ' MASKEDNUMBER '. Skipping.
WARNING: Could not find literal '-based company to improve their data - drive decision - make skill .' after placeholder ' location'. Skipping.
WARNING: Could not find literal ' 's research on conformity and obedience .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
INFO: No literal after placeholder '[ name ]'. Skipping.
WARNING: Could not find literal ' 's outsource project . can you help ?' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal 's ?' after placeholder ' job'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' . think it might be useful for your sustainability effort .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' involve the disputed ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal 's , to be send to ' after placeholder ' job'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' . can you help I draft the group description and guideline ?' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' be startup ?' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' . can you write a brief review of its feature and benefit ?' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' ’s company website .' after placeholder ' name '. Skipping.
WARNING: Could not find literal 's on how to effectively use the crm system to manage customer relationship .' after placeholder ' job'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' url '. Skipping.
WARNING: Could not find literal ' headquarter , and how it affect decision - making .' after placeholder ' LOCATION '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' 's team to improve communication in their office at ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' 's ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' 's university , focus on ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal '-based organization .' after placeholder ' location'. Skipping.
WARNING: Could not find literal ' . can you give I some insight ?' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' . can you help I find more online forum where this topic be discuss ?' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' 's order from the ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' be startup with a focus on cost structure and customer relationship ?' after placeholder ' name '. Skipping.
INFO: No literal after placeholder '[ name ]'. Skipping.
WARNING: Could not find literal ' 's patient at ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' in manage conflict of interest within the organization .' after placeholder ' JOB '. Skipping.
WARNING: Could not find literal '-based startup .' after placeholder ' location'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
INFO: No literal after placeholder '[ name ]'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' 's business in the ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' . please send it to ' after placeholder ' URL '. Skipping.
WARNING: Could not find literal 's when work with patient with personality disorder .' after placeholder ' JOB'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' IBAN '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' over the disputed ' after placeholder ' name '. Skipping.
WARNING: Could not find literal '-based company .' after placeholder ' location'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' datum protection act .' after placeholder ' LOCATION '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' be last ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' regard the disputed ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' 's medical practice .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' . they be injure in a car accident on ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' offer condolence and suggest trauma counseling service .' after placeholder ' location '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' live at ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' , ' after placeholder ' location '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal 's must keep in mind during family therapy session .' after placeholder ' job'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' . can you help I with the agenda ?' after placeholder ' name '. Skipping.
WARNING: Could not find literal 's in improve the quality of life for patient with chronic pain .' after placeholder ' job'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' legislation on datum protection and its impact on ' after placeholder ' location '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' . send it to their email at ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' 's upcoming training session ?' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' . can you help ?' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' . can you take a look and share your thought ?' after placeholder ' url '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal '-related issue .' after placeholder ' job'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' advocate for the inclusion of psycho - oncology service in cancer treatment center .' after placeholder ' email '. Skipping.
WARNING: Could not find literal ' loves listen to they and need new one to check out .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' . can you give I a summary ?' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' in phishing attack .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' , consider the expected income ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' to prepare for their child custody hear in ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' be startup in the ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' 's upcoming workshop on humanistic therapy .' after placeholder ' name '. Skipping.
INFO: No literal after placeholder '[ name ]'. Skipping.
WARNING: Could not find literal ' base on the patient information provide in the attached ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' datum .' after placeholder ' IP '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' discuss the implication of a new administrative law rule in ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' share ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' with unauthorized individual .' after placeholder ' password '. Skipping.
WARNING: Could not find literal ' 's business use the datum from their ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' highlight the key achievement of their social responsibility program in ' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' .' after placeholder ' name '. Skipping.
WARNING: Could not find literal ' . can you give I a summary of the main point ?' after placeholder ' URL '. Skipping.
WARNING: Could not find literal '-based company use business analytic to increase its market share .' after placeholder ' location'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' vulnerability .' after placeholder ' IP '. Skipping.
WARNING: Could not find literal ' in datum breach .' after placeholder ' password '. Skipping.
WARNING: Could not find literal '-base server .' after placeholder ' ip'. Skipping.
WARNING: Could not find literal 's in provide behavioral therapy to patient in ' after placeholder ' job'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
INFO: No literal after placeholder '[ location ]'. Skipping.
WARNING: Could not find literal ' 's reference .' after placeholder ' name '. Skipping.
WARNING: Could not find literal '-base business .' after placeholder ' location'. Skipping.
WARNING: Could not find literal 's in the ' after placeholder ' job'. Skipping.
WARNING: Could not find literal ' .' after placeholder ' URL '. Skipping.
WARNING: Could not find literal ' be startup in the tech industry , include market analysis and financial projection .' after placeholder ' name '. Skipping.
WARNING: Could not find literal '-based company ?' after placeholder ' location'. Skipping.
WARNING: Could not find literal ' on informed consent in the medical field .' after placeholder ' name '. Skipping.
WARNING: Could not find literal 's to enhance their customer relationship management skill .' after placeholder ' job'. Skipping.

In [66]:
for key, ds_obj in datasets.items():
    # Create a copy of the test dataset and add new columns.
    ds = ds_obj.testing_data.copy()
    ds["original_text"] = ds["Filled Template"]
    ds["labeled_text"] = ds["Template"]
    ds["masked_text"] = ds["Filled Template"].apply(lambda x: mask_pii(x, ds_obj.nlp))
    
    # Save the new dataset to CSV
    ds_to_save = ds[["original_text", "labeled_text", "masked_text"]]
    output_filename = f"dataset_{ds_obj.name}.csv"
    ds_to_save.to_csv(output_filename, index=False)
    print(f"Saved {output_filename}")

Saved dataset_1.csv

# EVAL

In [69]:
import pandas as pd
import re
from difflib import SequenceMatcher

# Define the set of known placeholders.
PLACEHOLDERS = {"NAME", "LOCATION", "EMAIL", "JOB", "MASKEDNUMBER",
                "URL", "USERNAME", "IP", "PASSWORD", "GENDER",
                "CREDITCARDNUMBER", "USERAGENT", "IBAN", "BIC"}

def extract_masked_tokens(text, return_positions=False):
    """
    Extracts all masked tokens that match known placeholders.
    If return_positions is True, returns a list of tuples (token, start, end).
    Otherwise, returns just the list of token strings.
    """
    pattern = re.compile(r'\b(' + '|'.join(PLACEHOLDERS) + r')\b', re.IGNORECASE)
    if return_positions:
        return [(m.group(), m.start(), m.end()) for m in pattern.finditer(text)]
    else:
        return pattern.findall(text)

def map_gold_span_to_pred(gold, pred, g_start, g_end):
    """
    Maps a span (g_start, g_end) from the gold text to the corresponding span in the predicted text
    using SequenceMatcher to align the two strings.
    Returns a tuple (pred_start, pred_end). If mapping fails, returns (None, None).
    """
    sm = SequenceMatcher(None, gold, pred)
    opcodes = sm.get_opcodes()
    pred_start = None
    pred_end = None
    for tag, i1, i2, j1, j2 in opcodes:
        # Map the start of the gold token.
        if g_start >= i1 and g_start < i2:
            if tag in ("equal", "replace"):
                pred_start = j1 + (g_start - i1)
            else:
                pred_start = j1
        # Map the end of the gold token.
        if g_end > i1 and g_end <= i2:
            if tag in ("equal", "replace"):
                pred_end = j1 + (g_end - i1)
            else:
                pred_end = j1
        if pred_start is not None and pred_end is not None:
            break
    return pred_start, pred_end

def analyze_row_aligned(original, gold, pred):
    """
    For each gold token, maps its span to the predicted text and then:
      1. Checks if a valid label (one of PLACEHOLDERS) is present at that location.
      2. If a valid label is found, compares it with the gold token:
           - If they match (ignoring case), counts as correct.
           - If they differ, counts as a misplaced token.
      3. If no valid label is found at the mapped span or mapping fails, counts as missing.
    Additionally, any extra valid tokens in the predicted text that do not correspond to any gold token
    are marked as false positives.
    
    Returns:
      - metrics: dictionary with counts for correct, misplaced, missing, false_positive.
      - examples: dictionary of examples for error cases.
    """
    gold_tokens = extract_masked_tokens(gold, return_positions=True)
    metrics = {"correct": 0, "misplaced": 0, "missing": 0, "false_positive": 0}
    examples = {"misplaced": []}
    
    # For each gold token, map its span to the predicted text.
    for idx, (g_token, g_start, g_end) in enumerate(gold_tokens):
        p_start, p_end = map_gold_span_to_pred(gold, pred, g_start, g_end)
        if p_start is None or p_end is None or p_start < 0 or p_end > len(pred):
            metrics["missing"] += 1
            examples["misplaced"].append({
                "gold": g_token,
                "predicted": None,
                "gold_span": (g_start, g_end),
                "pred_span": None,
                "note": "Mapping not found"
            })
        else:
            # Extract the predicted token and strip extra spaces.
            pred_token = pred[p_start:p_end].strip()
            valid_labels = {p.lower() for p in PLACEHOLDERS}
            if pred_token.lower() not in valid_labels:
                metrics["missing"] += 1
                examples["misplaced"].append({
                    "gold": g_token,
                    "predicted": pred_token,
                    "gold_span": (g_start, g_end),
                    "pred_span": (p_start, p_end),
                    "note": "No valid label found at mapped span"
                })
            else:
                if pred_token.lower() == g_token.lower():
                    metrics["correct"] += 1
                else:
                    metrics["misplaced"] += 1
                    examples["misplaced"].append({
                        "gold": g_token,
                        "predicted": pred_token,
                        "gold_span": (g_start, g_end),
                        "pred_span": (p_start, p_end),
                        "note": "Wrong label"
                    })
    
    # Identify extra predicted tokens not mapped from any gold token.
    pred_tokens = extract_masked_tokens(pred, return_positions=True)
    mapped_spans = []
    for (g_token, g_start, g_end) in gold_tokens:
        p_span = map_gold_span_to_pred(gold, pred, g_start, g_end)
        if p_span[0] is not None and p_span[1] is not None:
            mapped_spans.append(p_span)
    for p_token, p_start, p_end in pred_tokens:
        if not any(p_start == m[0] and p_end == m[1] for m in mapped_spans):
            metrics["false_positive"] += 1
            examples["misplaced"].append({
                "gold": None,
                "predicted": p_token,
                "gold_span": None,
                "pred_span": (p_start, p_end),
                "note": "Extra predicted token"
            })
            
    return metrics, examples

def analyze_masking(file_path, original_col=None, gold_col=None, pred_col=None):
    """
    Reads a file (CSV or pickle) that contains your evaluation results. The file is assumed to contain a pandas
    DataFrame with the columns for:
      - Original Text (the unmasked filled text),
      - Labeled Text (the gold masked template), and
      - Masked Text (the predicted masked template).
    
    The defaults are set to:
      - original_col: "original_text"
      - gold_col: "labeled_text"
      - pred_col: "masked_text"
    
    It then prints per-row metrics and aggregates overall evaluation metrics (Precision, Recall, F1, Accuracy).
    """
    # Read the file based on its extension.
    if file_path.endswith('.csv'):
        df = pd.read_csv(file_path)
    else:
        df = pd.read_pickle(file_path)
    
    # If the file is wrapped inside an object with a 'dataset' attribute, extract it.
    if hasattr(df, "dataset"):
        df = df.dataset

    # Print available columns for debugging.
    print("Available columns in the DataFrame:", df.columns.tolist())
    
    # Determine column names if not provided.
    if original_col is None:
        if "original_text" in df.columns:
            original_col = "original_text"
        else:
            raise ValueError("Could not determine original text column. Available columns: " + str(df.columns.tolist()))
    
    if gold_col is None:
        if "labeled_text" in df.columns:
            gold_col = "labeled_text"
        else:
            raise ValueError("Could not determine gold masked text column. Available columns: " + str(df.columns.tolist()))
    
    if pred_col is None:
        if "masked_text" in df.columns:
            pred_col = "masked_text"
        else:
            raise ValueError("Could not determine predicted masked text column. Available columns: " + str(df.columns.tolist()))
    
    # Verify the required columns exist.
    required_columns = [original_col, gold_col, pred_col]
    if not all(col in df.columns for col in required_columns):
        raise ValueError(f"DataFrame does not contain the required columns: {required_columns}")

    all_metrics = {"correct": 0, "misplaced": 0, "missing": 0, "false_positive": 0}
    all_examples = {"misplaced": []}
    detailed_results = []
    
    # Process each row.
    for idx, row in df.iterrows():
        metrics, examples = analyze_row_aligned(
            row[original_col],
            row[gold_col],
            row[pred_col]
        )
        detailed_results.append(metrics)
        for key in all_metrics:
            all_metrics[key] += metrics.get(key, 0)
        for ex in examples["misplaced"]:
            ex["row"] = idx
            ex["original"] = row[original_col]
            ex["labeled_text"] = row[gold_col]
            ex["masked_text"] = row[pred_col]
            all_examples["misplaced"].append(ex)
    
    metrics_df = pd.DataFrame(detailed_results)
    print("\nPer-row masking metrics:")
    print(metrics_df)
    
    print("\nAggregate masking metrics:")
    for key, value in all_metrics.items():
        print(f"{key}: {value}")
    
    note_counts = {"No valid label found at mapped span": 0, "Extra predicted token": 0}
    for ex in all_examples["misplaced"]:
        note = ex.get("note", "")
        if note in note_counts:
            note_counts[note] += 1

    print("\nCount of tokens with note 'No valid label found at mapped span':", 
          note_counts["No valid label found at mapped span"])
    print("Count of tokens with note 'Extra predicted token':", 
          note_counts["Extra predicted token"])
    
    print("\nExamples of Misplaced Tokens:")
    if all_examples["misplaced"]:
        for ex in all_examples["misplaced"]:
            print(f"Row {ex['row']} | Original Text:  {ex['original']}")
            print(f"Row {ex['row']} | Labeled Text:   {ex['labeled_text']}")
            print(f"Row {ex['row']} | Masked Text:    {ex['masked_text']}")
            print(f"  Note: {ex.get('note', '')}")
            print(f"  Gold: '{ex['gold']}' at {ex['gold_span']} vs Predicted: '{ex['predicted']}' at {ex['pred_span']}\n")
    else:
        print("No misplaced tokens found.")
    
    print(f"\nAmount of Misplaced Tokens: {len(all_examples['misplaced'])}")
    
    # Calculate evaluation metrics.
    TP = all_metrics["correct"]
    FN = all_metrics["missing"] + all_metrics["misplaced"]
    FP = all_metrics["false_positive"] + all_metrics["misplaced"]
    
    precision = TP / (TP + FP) if (TP + FP) > 0 else 0
    recall = TP / (TP + FN) if (TP + FN) > 0 else 0
    F1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
    accuracy = TP / (TP + FP + FN) if (TP + FP + FN) > 0 else 0
    
    print("\nEvaluation Metrics:")
    print(f"Precision: {precision:.3f}")
    print(f"Recall: {recall:.3f}")
    print(f"F1 Score: {F1:.3f}")
    print(f"Accuracy: {accuracy:.3f}")
    
    return all_metrics, metrics_df, all_examples

if __name__ == "__main__":
    # For a CSV file with columns: original_text, labeled_text, masked_text located in /tests,
    # the defaults will map as:
    #   original_col = "original_text"
    #   gold_col = "labeled_text"
    #   pred_col = "masked_text"
    aggregate_metrics, per_row_metrics, examples = analyze_masking("dataset_1.csv")

Available columns in the DataFrame: ['original_text', 'labeled_text', 'masked_text']

Per-row masking metrics:
      correct  misplaced  missing  false_positive
0           2          0        0               1
1           3          0        0               0
2           1          0        0               0
3           2          0        0               0
4           2          0        0               0
...       ...        ...      ...             ...
4265        1          0        0               0
4266        1          0        0               0
4267        4          0        0               0
4268        1          0        0               0
4269        4          0        0               0

[4270 rows x 4 columns]

Aggregate masking metrics:
correct: 8788
misplaced: 15
missing: 129
false_positive: 102

Count of tokens with note 'No valid label found at mapped span': 124
Count of tokens with note 'Extra predicted token': 102

Examples of Misplaced Tokens:
Row 0 | Original Text:  let we discuss the defense mechanism employ by glen heathcote in response to their unconscious desire during our video conference .
Row 0 | Labeled Text:   let we discuss the defense mechanism employ by [ name ] [ name ] in response to their unconscious desire during our video conference .
Row 0 | Masked Text:    let we discuss the defense mechanism employ by [ name ] [ name ] in [ JOB ] to their unconscious desire during our video conference .
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'JOB' at (70, 73)

Row 39 | Original Text:  draft a letter to kirlin - zieme at 8247 shaylee fork , jazminborough , 85812 - 8481 explain the eligibility criterion for chapter 13 bankruptcy .
Row 39 | Labeled Text:   draft a letter to [ name ] at [ location ] , [ LOCATION ] , [ location ] explain the eligibility criterion for chapter 13 bankruptcy .
Row 39 | Masked Text:    draft a letter to [ name ] at [ location ] [ LOCATION ] , [ LOCATION ] , [ location ] explain the eligibility criterion for chapter 13 bankruptcy .
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'LOCATION' at (45, 53)

Row 64 | Original Text:  hey , nathen be look for some advice on implement a quality management system , can you help ?
Row 64 | Labeled Text:   hey , [ name ] be look for some advice on implement a quality management system , can you help ?
Row 64 | Masked Text:    hey , nathen be look for some advice on implement a quality management system , can you help ?
  Note: No valid label found at mapped span
  Gold: 'name' at (8, 12) vs Predicted: 'nathe' at (6, 11)

Row 81 | Original Text:  please create a risk assessment of outsource our manufacture operation to watersport for leah kuphal i.
Row 81 | Labeled Text:   please create a risk assessment of outsource our manufacture operation to [ location ] for [ name ] [ name ] .
Row 81 | Masked Text:    please create a risk assessment of outsource our manufacture operation to [ location ] for [ name ] kuphal i.
  Note: Mapping not found
  Gold: 'name' at (102, 106) vs Predicted: 'None' at None

Row 93 | Original Text:  hey , can you explain the process of filing for bankruptcy ? make sure to include how zambian kwacha and 97366738 would be affect .
Row 93 | Labeled Text:   hey , can you explain the process of filing for bankruptcy ? make sure to include how zambian kwacha and [ MASKEDNUMBER ] would be affect .
Row 93 | Masked Text:    hey , can you explain the process of filing for bankruptcy ? make sure to include how zambian kwacha and [ CREDITCARDNUMBER ] would be affect .
  Note: Wrong label
  Gold: 'MASKEDNUMBER' at (107, 119) vs Predicted: 'CREDITCARDNUMBER' at (107, 123)

Row 96 | Original Text:  draft a press release for haye , armstrong and kuphal announce the opening of their new humanistic therapy practice , include the 4573 and contact information .
Row 96 | Labeled Text:   draft a press release for [ name ] announce the opening of their new humanistic therapy practice , include the [ location ] and contact information .
Row 96 | Masked Text:    draft a press release for [ name ] announce the opening of their new humanistic therapy practice , include the [ MASKEDNUMBER ] and contact information .
  Note: No valid label found at mapped span
  Gold: 'location' at (113, 121) vs Predicted: 'MASKEDNU' at (113, 121)

Row 96 | Original Text:  draft a press release for haye , armstrong and kuphal announce the opening of their new humanistic therapy practice , include the 4573 and contact information .
Row 96 | Labeled Text:   draft a press release for [ name ] announce the opening of their new humanistic therapy practice , include the [ location ] and contact information .
Row 96 | Masked Text:    draft a press release for [ name ] announce the opening of their new humanistic therapy practice , include the [ MASKEDNUMBER ] and contact information .
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'MASKEDNUMBER' at (113, 125)

Row 170 | Original Text:  can you help wolff group understand the difference between gdpr and the data protection act 2018 ?
Row 170 | Labeled Text:   can you help [ name ] understand the difference between gdpr and the data protection act 2018 ?
Row 170 | Masked Text:    can you help [ name ] understand the difference between gdpr and the data protection act [ CREDITCARDNUMBER ] ?
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'CREDITCARDNUMBER' at (91, 107)

Row 223 | Original Text:  our customer osinski , macgyver and kuvalis be have issue with their account . can you write an email to michaela25@gmail.com with instruction on how to reset their uai6bbfih8vw ?
Row 223 | Labeled Text:   our customer [ NAME ] be have issue with their account . can you write an email to [ email ] with instruction on how to reset their [ password ] ?
Row 223 | Masked Text:    our customer [ name ] be have issue with their account . can you write an email to [ email ] with instruction on how to reset their uai6bbfih8vw ?
  Note: No valid label found at mapped span
  Gold: 'password' at (134, 142) vs Predicted: 'i6bbfih8vw' at (134, 144)

Row 234 | Original Text:  could you help I develop a training manual for our crisis intervention team at 978 gleichn rapid ?
Row 234 | Labeled Text:   could you help I develop a training manual for our crisis intervention team at [ location ] ?
Row 234 | Masked Text:    could you help I develop a training manual for our crisis intervention team at [ location ] [ location ] ?
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'location' at (94, 102)

Row 254 | Original Text:  can you create a legal document for pagac inc concern the property dispute at 59201 ronny way ?
Row 254 | Labeled Text:   can you create a legal document for [ name ] concern the property dispute at [ location ] [ location ] ?
Row 254 | Masked Text:    can you create a legal document for [ name ] concern the property dispute at [ location ] ?
  Note: No valid label found at mapped span
  Gold: 'location' at (92, 100) vs Predicted: '' at (90, 90)

Row 255 | Original Text:  5 . assign danny_oconnell70 and ait_lnkvy8po to paucek llc for access the company 's internal network .
Row 255 | Labeled Text:   5 . assign [ USERNAME ] and [ password ] to [ name ] for access the company 's internal network .
Row 255 | Masked Text:    5 . assign [ USERNAME ] and [ URL ] to [ name ] for access the company 's internal network .
  Note: No valid label found at mapped span
  Gold: 'password' at (30, 38) vs Predicted: 'URL ] to' at (30, 38)

Row 255 | Original Text:  5 . assign danny_oconnell70 and ait_lnkvy8po to paucek llc for access the company 's internal network .
Row 255 | Labeled Text:   5 . assign [ USERNAME ] and [ password ] to [ name ] for access the company 's internal network .
Row 255 | Masked Text:    5 . assign [ USERNAME ] and [ URL ] to [ name ] for access the company 's internal network .
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'URL' at (30, 33)

Row 264 | Original Text:  write an article for mr . leon king on the role of the security and exchange commission ( sec ) in regulate the security market .
Row 264 | Labeled Text:   write an article for [ name ] [ name ] on the role of the security and exchange commission ( sec ) in regulate the security market .
Row 264 | Masked Text:    write an article for [ name ] [ name ] on the role of the security and exchange commission ( sec ) in regulate the [ JOB ] market .
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'JOB' at (117, 120)

Row 265 | Original Text:  what be the potential risk of combine fay llc with alcohol ? I have hear mixed opinion on this .
Row 265 | Labeled Text:   what be the potential risk of combine [ name ] with alcohol ? I have hear mixed opinion on this .
Row 265 | Masked Text:    what be the potential risk of [ name ] [ name ] with alcohol ? I have hear mixed opinion on this .
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'name' at (32, 36)

Row 275 | Original Text:  hey german , I find this interesting blog post on the history of psychoeducation . give it a read here : https://acceptable-fratricide.info/
Row 275 | Labeled Text:   hey [ name ] , I find this interesting blog post on the history of psychoeducation . give it a read here : [ url ]
Row 275 | Masked Text:    hey [ name ] , I find this interesting blog post on the history of psychoeducation . give it a read here : https://acceptable-fratricide.info/
  Note: No valid label found at mapped span
  Gold: 'url' at (109, 112) vs Predicted: 'tps://acceptable-fra' at (109, 129)

Row 304 | Original Text:  can you compile a list of international law resource and reference for mrs . shannon turcotte to use in their web research ?
Row 304 | Labeled Text:   can you compile a list of international law resource and reference for [ name ] [ name ] to use in their [ JOB ] research ?
Row 304 | Masked Text:    can you compile a list of international law resource and reference for [ name ] [ name ] to use in their web research ?
  Note: No valid label found at mapped span
  Gold: 'JOB' at (107, 110) vs Predicted: 'b r' at (107, 110)

Row 311 | Original Text:  create a list of emergency contact , include their hansen , o'connell and goldner and 1 - 608 - 478 - 0087 x30971 , for tulsa crisis intervention team .
Row 311 | Labeled Text:   create a list of emergency contact , include their [ name ] and [ MASKEDNUMBER ] , for [ location ] crisis intervention team .
Row 311 | Masked Text:    create a list of emergency contact , include their [ name ] and [ MASKEDNUMBER ] , for [ name ] crisis intervention team .
  Note: No valid label found at mapped span
  Gold: 'location' at (89, 97) vs Predicted: 'name ]' at (89, 95)

Row 311 | Original Text:  create a list of emergency contact , include their hansen , o'connell and goldner and 1 - 608 - 478 - 0087 x30971 , for tulsa crisis intervention team .
Row 311 | Labeled Text:   create a list of emergency contact , include their [ name ] and [ MASKEDNUMBER ] , for [ location ] crisis intervention team .
Row 311 | Masked Text:    create a list of emergency contact , include their [ name ] and [ MASKEDNUMBER ] , for [ name ] crisis intervention team .
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'name' at (89, 93)

Row 342 | Original Text:  develop a comprehensive guide for stark , lynch and crona on understand insurance law , with a focus on the right of policyholder with account number like 42593873 .
Row 342 | Labeled Text:   develop a comprehensive guide for [ name ] on understand insurance law , with a focus on the right of policyholder with account number like [ MASKEDNUMBER ] .
Row 342 | Masked Text:    develop a comprehensive guide for [ name ] on understand insurance law , with a focus on the right of policyholder with account number like [ CREDITCARDNUMBER ] .
  Note: Wrong label
  Gold: 'MASKEDNUMBER' at (142, 154) vs Predicted: 'CREDITCARDNUMBER' at (142, 158)

Row 344 | Original Text:  during the video conference , present the late research on animal - assist therapy to jonathan lehner and share finding from https://brown-tolerant.info/.
Row 344 | Labeled Text:   during the video conference , present the late research on animal - assist therapy to [ name ] [ name ] and share finding from [ URL ] .
Row 344 | Masked Text:    during the video conference , present the late research on animal - assist therapy to [ name ] [ name ] and share finding from https://brown-tolerant.info/.
  Note: No valid label found at mapped span
  Gold: 'URL' at (129, 132) vs Predicted: 'tps' at (129, 132)

Row 356 | Original Text:  write an article about the challenge and opportunity face by female entrepreneur , highlight the achievement of sidney koss and sophie moen .
Row 356 | Labeled Text:   write an article about the challenge and opportunity face by female entrepreneur , highlight the achievement of [ name ] [ name ] and [ name ] [ name ] .
Row 356 | Masked Text:    write an article about the challenge and opportunity face by [ GENDER ] entrepreneur , highlight the achievement of [ name ] [ name ] and [ name ] [ name ] .
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'GENDER' at (63, 69)

Row 364 | Original Text:  7 . legal implication of data merger and acquisition in rosaliaborough and bayleeport .
Row 364 | Labeled Text:   7 . legal implication of [ JOB ] merger and acquisition in [ location ] and [ location ] .
Row 364 | Masked Text:    7 . legal implication of data merger and acquisition in [ location ] and [ location ] .
  Note: No valid label found at mapped span
  Gold: 'JOB' at (27, 30) vs Predicted: 'ta' at (27, 30)

Row 374 | Original Text:  can you help kessler - bosco figure out the property taxis for a house at 66679 schumm key ?
Row 374 | Labeled Text:   can you help [ name ] figure out the property taxis for a house at [ location ] ?
Row 374 | Masked Text:    can you help [ name ] figure out the property taxis for a house at [ location ] [ location ] ?
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'location' at (82, 90)

Row 383 | Original Text:  can you provide a summary of the voting right act of 1965 for maggie yundt ? they be study civil right law at 82013 brennan dale .
Row 383 | Labeled Text:   can you provide a summary of the voting right act of 1965 for [ name ] [ name ] ? they be study civil right law at [ location ] .
Row 383 | Masked Text:    can you provide a summary of the voting right act of [ MASKEDNUMBER ] for [ name ] [ name ] ? they be study civil right law at [ location ] .
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'MASKEDNUMBER' at (55, 67)

Row 451 | Original Text:  draft a contract for ervin bernhard regard the sale of a residential property at 54524 kyla ferry , chico , 46409 .
Row 451 | Labeled Text:   draft a contract for [ name ] [ name ] regard the sale of a residential property at [ location ] , [ LOCATION ] , [ location ] .
Row 451 | Masked Text:    draft a contract for [ name ] [ name ] regard the sale of a residential property at [ location ] [ LOCATION ] , [ LOCATION ] , [ location ] .
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'LOCATION' at (99, 107)

Row 499 | Original Text:  create a resource guide for weissnat inc on adhd therapy option available in https://valuable-trip.name/.
Row 499 | Labeled Text:   create a resource guide for [ name ] on adhd therapy option available in [ URL ] .
Row 499 | Masked Text:    create a resource guide for [ name ] on adhd therapy option available in https://valuable-trip.name/.
  Note: No valid label found at mapped span
  Gold: 'URL' at (75, 78) vs Predicted: 'tps' at (75, 78)

Row 499 | Original Text:  create a resource guide for weissnat inc on adhd therapy option available in https://valuable-trip.name/.
Row 499 | Labeled Text:   create a resource guide for [ name ] on adhd therapy option available in [ URL ] .
Row 499 | Masked Text:    create a resource guide for [ name ] on adhd therapy option available in https://valuable-trip.name/.
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'name' at (95, 99)

Row 526 | Original Text:  18 . draft a press release for sandra stracke announce their new humanistic therapy practice at 20848 henderson courts , north tomasa .
Row 526 | Labeled Text:   18 . draft a press release for [ name ] [ name ] announce their new humanistic therapy practice at [ location ] , [ location ] .
Row 526 | Masked Text:    18 . draft a press release for [ name ] [ name ] announce their new humanistic therapy practice at [ location ] [ LOCATION ] , [ location ] .
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'LOCATION' at (114, 122)

Row 559 | Original Text:  draft a purchase agreement for kassulke , simonis and cole , include the property detail at 4044 jast isle and a down payment of 854.87 congolese franc .
Row 559 | Labeled Text:   draft a purchase agreement for [ name ] , include the property detail at [ location ] [ LOCATION ] and a down payment of [ MASKEDNUMBER ] congolese franc .
Row 559 | Masked Text:    draft a purchase agreement for [ name ] , include the property detail at [ location ] and a down payment of [ MASKEDNUMBER ] congolese franc .
  Note: No valid label found at mapped span
  Gold: 'LOCATION' at (88, 96) vs Predicted: '' at (86, 86)

Row 562 | Original Text:  provide a summary of the foreclosure process in colorado for jerde and son to review before consider a distressed property at 579 ericka extension .
Row 562 | Labeled Text:   provide a summary of the foreclosure process in [ location ] for [ name ] to review before consider a distressed property at [ location ] [ location ] .
Row 562 | Masked Text:    provide a summary of the foreclosure process in [ location ] for [ name ] to review before consider a distressed property at [ location ] .
  Note: No valid label found at mapped span
  Gold: 'location' at (140, 148) vs Predicted: '' at (138, 138)

Row 577 | Original Text:  8 . organize a press conference at 55199 cecilia passage , gardena , to announce our new partnership with miller and son .
Row 577 | Labeled Text:   8 . organize a press conference at [ location ] , [ LOCATION ] , to announce our new partnership with [ name ] .
Row 577 | Masked Text:    8 . organize a press conference at [ location ] [ LOCATION ] , [ LOCATION ] , to announce our new partnership with [ name ] .
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'LOCATION' at (50, 58)

Row 578 | Original Text:  17 . describe the potential role of mediation as an alternative to arbitration for mr . jackie ernser and willard turcotte v.
Row 578 | Labeled Text:   17 . describe the potential role of mediation as an alternative to arbitration for [ name ] [ name ] and [ name ] [ name ] .
Row 578 | Masked Text:    17 . describe the potential role of mediation as an alternative to arbitration for [ name ] [ name ] and [ name ] turcotte v.
  Note: No valid label found at mapped span
  Gold: 'name' at (116, 120) vs Predicted: 'rcotte' at (116, 122)

Row 580 | Original Text:  hi jaime wuckert - rath , please send I the list of item that have be delay in transit . we need to inform our customer about the update delivery date .
Row 580 | Labeled Text:   hi [ name ] [ name ] , please send I the list of item that have be delay in transit . we need to inform our customer about the update delivery date .
Row 580 | Masked Text:    hi [ name ] [ name ] , please send I the list of item that have be delay in [ location ] . we need to inform our customer about the update delivery date .
  Note: Extra predicted token
  Gold: 'None' at None vs Predicted: 'location' at (78, 86)

Row 610 | Original Text:  can you help I draft a document outline the ethical consideration for lawyer when deal with client who have 35kdvxr9kvpvensyxfythyrwtd6fuun ?

In [70]:
#print  csv  masked_text, dataset_1.csv

#read csv file
df = pd.read_csv("dataset_1.csv")
#labeled_text
print(df.labeled_text[1])
print(df.masked_text[1])

write a research proposal for [ name ] [ name ] to study the social impact of immigration in [ location ] .
write a research proposal for [ name ] [ name ] to study the social impact of immigration in [ location ] .